import { useCallback, useEffect, useState, type RefObject } from "react";
import type { EditorRef } from "@/components/editor/core/Editor";
import { renderMermaidSvgForExport } from "@/lib/imageExport/mermaid";
import { svgMarkupToPngBlob } from "@/lib/imageExport/svgToPng";
import { ArtifactActions } from "./ArtifactActions";
import { ArtifactPanZoom } from "./ArtifactPanZoom";
import { createMermaidArtifactBlocks, insertArtifactBlocks } from "./insertArtifact";
import { useSettings } from "@/stores/useSettings";
import { useResolvedTheme } from "@/hooks/useResolvedTheme";

interface DiagramCardProps {
  title?: string;
  source: string;
  editorRef?: RefObject<EditorRef | null>;
}

export function DiagramCard({ title, source, editorRef }: DiagramCardProps) {
  const theme = useSettings((state) => state.theme);
  const resolvedTheme = useResolvedTheme(theme);
  const [svg, setSvg] = useState("");
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let active = true;

    const render = async () => {
      setFailed(false);
      try {
        const nextSvg = await renderMermaidSvgForExport(source, resolvedTheme);
        if (active) setSvg(nextSvg);
      } catch {
        if (active) {
          setSvg("");
          setFailed(true);
        }
      }
    };

    if (source.trim()) void render();
    return () => {
      active = false;
    };
  }, [resolvedTheme, source]);

  const capturePng = useCallback(async () => {
    const markup =
      svg ||
      (await renderMermaidSvgForExport(source, resolvedTheme));
    if (!markup.trim()) throw new Error("图形尚未就绪");
    return svgMarkupToPngBlob(markup);
  }, [resolvedTheme, source, svg]);

  return (
    <div className="group relative my-2 overflow-hidden rounded-[8px] bg-[var(--goose-interactive-hover)]">
      <ArtifactActions
        copySource={source}
        onCopyImage={async () => capturePng()}
        onDownloadImage={capturePng}
        downloadImageFilename="diagram.png"
        onInsert={() =>
          insertArtifactBlocks(
            editorRef,
            createMermaidArtifactBlocks(title, source),
          )
        }
      />
      {title ? (
        <div className="px-3 py-2 text-xs font-medium text-foreground">
          {title}
        </div>
      ) : null}
      {svg ? (
        <ArtifactPanZoom contentKey={`${resolvedTheme}:${source}`} minHeight={280}>
          <div
            aria-hidden="true"
            className="notebook-ai-artifact-svg"
            // Mermaid output is generated by the local renderer, not raw model HTML.
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        </ArtifactPanZoom>
      ) : failed ? (
        <div className="flex min-h-[180px] items-center justify-center px-3 py-4 text-xs text-muted-foreground">
          图形生成失败
        </div>
      ) : (
        <div className="flex min-h-[180px] items-center justify-center px-3 py-4 text-xs text-muted-foreground">
          正在生成图形
        </div>
      )}
    </div>
  );
}
