import path from "node:path";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import {
  createUnimport,
  toTypeDeclarationFile,
  toTypeReExports,
  type Import,
} from "unimport";
import { autoImportEntries } from "./autoImportEntries";
import { autoImportPackages } from "./autoImportPackages";
import { scanPublicImports } from "./autoImportScanner";

const GENERATED_HEADER =
  "// Generated by Goose Note auto-import configuration.\n";
const LEAF_HEADER = `${GENERATED_HEADER}/* eslint-disable */\n/* prettier-ignore */\n// @ts-nocheck\n`;
const MAX_DECLARATION_LINES = 300;

function declarationGroup(item: Import, root: string): string {
  const from = path.relative(root, item.from).replaceAll("\\", "/");
  if (from.startsWith("src/components/editor/")) return "editor";
  if (from.startsWith("src/components/ui/")) return "ui";
  if (from.startsWith("src/hooks/")) return "hooks";
  if (from.startsWith("src/stores/")) return "stores";
  if (from.startsWith("src/lib/")) return "lib";
  return "packages";
}

function generateLeaf(imports: Import[], directory: string): string {
  const options = {
    resolvePath(item: Import) {
      const from = item.typeFrom || item.from;
      if (!path.isAbsolute(from)) return from;
      const relative = path
        .relative(directory, from)
        .replaceAll("\\", "/")
        .replace(/\.tsx?$/, "");
      return relative.startsWith(".") ? relative : `./${relative}`;
    },
  };
  const values = imports.filter((item) => !item.type && !item.dtsDisabled);
  const types = imports.filter((item) => item.type);
  return `${LEAF_HEADER}${toTypeDeclarationFile(values, options)}${types.length ? `\n${toTypeReExports(types, options)}` : ""}\n`;
}

async function writeIfChanged(file: string, content: string) {
  const current = await readFile(file, "utf8").catch(() => "");
  if (current !== content) await writeFile(file, content, "utf8");
}

function assertUniquePublicImports(imports: Import[]) {
  const names = new Map<string, Import>();
  for (const item of imports) {
    const key = `${item.as ?? item.name}:${Boolean(item.type)}`;
    const previous = names.get(key);
    if (
      previous &&
      (previous.from !== item.from || previous.name !== item.name)
    ) {
      throw new Error(
        `[auto-import] 公共符号 ${item.as ?? item.name} 同时从 ${previous.from} 和 ${item.from} 导出。请保留唯一公开入口。`,
      );
    }
    names.set(key, item);
  }
}

/** 每次重新扫描公开入口，删除项不会像 append 模式一样留在声明中。 */
export async function generateAutoImportDeclarations(root: string) {
  const missing = autoImportEntries.filter(
    (entry) => !existsSync(path.join(root, entry)),
  );
  if (missing.length) {
    throw new Error(
      `[auto-import] 公共入口已不存在，请更新 autoImportEntries：${missing.join(", ")}`,
    );
  }
  const packageImports = Object.entries(autoImportPackages).flatMap(
    ([from, names]) => names.map((name) => ({ from, name, as: name })),
  );
  const scanned = await scanPublicImports(autoImportEntries, root);
  assertUniquePublicImports([...packageImports, ...scanned]);
  const unimport = createUnimport({ imports: packageImports });
  await unimport.modifyDynamicImports(() => scanned);
  const imports = await unimport.getImports();
  const directory = path.join(root, "src/auto-imports");
  await mkdir(directory, { recursive: true });
  const groups = new Map<string, Import[]>();
  for (const item of imports) {
    const group = declarationGroup(item, root);
    groups.set(group, [...(groups.get(group) ?? []), item]);
  }
  const files: string[] = [];
  for (const [group, items] of [...groups].sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    items.sort((a, b) =>
      `${a.from}:${a.as}:${a.type}`.localeCompare(
        `${b.from}:${b.as}:${b.type}`,
      ),
    );
    let batch: Import[] = [];
    let part = 1;
    const flush = async () => {
      if (!batch.length) return;
      const filename = `${group}-${part++}.d.ts`;
      files.push(filename);
      await writeIfChanged(
        path.join(directory, filename),
        generateLeaf(batch, directory),
      );
      batch = [];
    };
    for (const item of items) {
      const candidate = [...batch, item];
      if (
        generateLeaf(candidate, directory).trimEnd().split("\n").length >
        MAX_DECLARATION_LINES
      )
        await flush();
      batch.push(item);
    }
    await flush();
  }
  for (const filename of await readdir(directory)) {
    if (!filename.endsWith(".d.ts") || files.includes(filename)) continue;
    const file = path.join(directory, filename);
    if ((await readFile(file, "utf8")).startsWith(GENERATED_HEADER))
      await rm(file);
  }
  await writeIfChanged(
    path.join(root, "src/auto-imports.d.ts"),
    GENERATED_HEADER +
      files
        .map(
          (file) => `import "./auto-imports/${file.replace(/\.d\.ts$/, "")}";`,
        )
        .join("\n") +
      "\n",
  );
}
