/** 与现有 unplugin-auto-import React preset 相同的公开 API。 */
export const autoImportPackages = {
  react: [
    "useState",
    "useCallback",
    "useMemo",
    "useEffect",
    "useRef",
    "useContext",
    "useReducer",
    "useImperativeHandle",
    "useDebugValue",
    "useDeferredValue",
    "useLayoutEffect",
    "useTransition",
    "startTransition",
    "useSyncExternalStore",
    "useInsertionEffect",
    "useId",
    "lazy",
    "memo",
    "createRef",
    "forwardRef",
    "cache",
    "cacheSignal",
    "createContext",
    "use",
    "useOptimistic",
    "useEffectEvent",
    "useActionState",
    "Fragment",
    "Suspense",
    "Activity",
  ],
  clsx: ["clsx"],
};
