export {
  type Theme,
  ACCENT_COLORS,
  type AccentColor,
  DEFAULT_ACCENT_COLOR,
  type CodeTheme,
  type FontConfig,
  type CustomFonts,
  type UIFontSize,
  UI_SCALE_MIN,
  UI_SCALE_MAX,
  UI_FONT_SIZE_BASE,
  EDITOR_FONT_SIZE_MIN,
  EDITOR_FONT_SIZE_MAX,
  EDITOR_FONT_SIZE_DEFAULT,
  EDITOR_LINE_HEIGHT_MIN,
  EDITOR_LINE_HEIGHT_MAX,
  EDITOR_LINE_HEIGHT_DEFAULT,
  normalizeEditorLineHeight,
  SIDEBAR_FONT_SIZE_MIN,
  SIDEBAR_FONT_SIZE_MAX,
  SIDEBAR_FONT_SIZE_DEFAULT,
  normalizeEditorFontSize,
  normalizeSidebarFontSize,
  DEFAULT_UI_FONT_SIZE,
  normalizeAccentColor,
  resolveCodeTheme,
  normalizeUIFontSize,
} from "./types/appearance";
export {
  type AIAgentRuntime,
  type AISettings,
  normalizeAIModelOptions,
  normalizeAIBaseURL,
  normalizeAIApiKey,
  normalizeAIReasoningLevel,
  normalizeAISettings,
} from "./types/ai";
export {
  type DesktopHotkeyStatusState,
  type DesktopHotkeyStatus,
  type DesktopSettings,
  type PrivacySettings,
  DEFAULT_WAKE_HOTKEY,
  DEFAULT_SEARCH_HOTKEY,
  DEFAULT_QUICKNOTE_HOTKEY,
  LEGACY_DEFAULT_QUICKNOTE_HOTKEY,
  DEFAULT_CLOSE_TAB_SHORTCUT,
  DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT,
  ELECTRON_WINDOW_HEIGHT_MIN,
  ELECTRON_WINDOW_HEIGHT_MAX,
  ELECTRON_WINDOW_HEIGHT_DEFAULT,
  AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN,
  AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX,
  AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT,
  DEFAULT_HOTKEY_STATUS,
  normalizeDesktopHotkeyStatus,
  mergeDesktopSettings,
  normalizeAutoCloseInactiveTabsHours,
} from "./types/desktop";
export {
  type SearchProvider,
  DEFAULT_SEARCH_PROVIDERS,
  mergeSearchProvidersWithDefaults,
  getSearchProviderTemplateError,
} from "./types/search";
export {
  type CustomAction,
  LEGACY_DEFAULT_CUSTOM_ACTION_ID,
  normalizeCustomActions,
} from "./types/customActions";
