import type { CardTheme } from "./types";

// ── Card Theme Presets ─────────────────────────────────────────
// 20 curated visual themes for the share card, designed for 2025-2026

export const CARD_THEMES: CardTheme[] = [
  // ── 1. Notion ────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion 白",
    nameEn: "Notion",
    description: "极简专业，文档感",
    tags: ["极简", "文档"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 700,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#37352f",
    secondaryText: "#9ca3af",
    accent: "#2d6cdf",
    codeBg: "#f5f5f5",
    quoteBorder: "#e5e7eb",
    calloutBg: "#f9fafb",
    tableBorder: "#e5e7eb",
    divider: "#e5e7eb",
    watermark: "#e0e0e0",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #f0f0f0",
    cardShadow: "0 1px 3px rgba(0,0,0,0.02), 0 4px 12px rgba(0,0,0,0.03)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 2. Obsidian ──────────────────────────────────────────────
  {
    id: "obsidian",
    name: "Obsidian 夜",
    nameEn: "Obsidian",
    description: "深色模式，代码感",
    tags: ["深色", "技术"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 700,
    titleLineHeight: 1.35,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "linear-gradient(160deg, #0d1117 0%, #161b22 50%, #0d1117 100%)",
    cardBg: "#161b22",
    textColor: "#e6edf3",
    secondaryText: "#7d8590",
    accent: "#58a6ff",
    codeBg: "#0d1117",
    quoteBorder: "#30363d",
    calloutBg: "#21262d",
    tableBorder: "#30363d",
    divider: "#30363d",
    watermark: "#6e7681",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #30363d",
    cardShadow: "0 8px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.03)",
    showDecorations: true,
    decorationColor: "rgba(88,166,255,0.06)",
    watermarkVisible: true,
  },

  // ── 3. Medium ────────────────────────────────────────────────
  {
    id: "medium",
    name: "Medium 杂志",
    nameEn: "Medium",
    description: "衬线大标题，阅读感",
    tags: ["杂志", "阅读"],
    mode: "light",
    titleFont: "'Noto Serif SC', 'Georgia', 'Times New Roman', serif",
    bodyFont: "'Noto Serif SC', 'Georgia', 'Times New Roman', serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 34,
    titleFontWeight: 400,
    titleLineHeight: 1.2,
    titleLetterSpacing: "-0.01em",
    titleAlign: "center",
    bodyFontSize: 16,
    bodyLineHeight: 1.9,
    bodyLetterSpacing: "0.01em",
    background: "#faf9f6",
    cardBg: "#ffffff",
    textColor: "#292929",
    secondaryText: "#757575",
    accent: "#1a8917",
    codeBg: "#f7f7f7",
    quoteBorder: "#e5e5e5",
    calloutBg: "#f9f9f9",
    tableBorder: "#e5e5e5",
    divider: "#e5e5e5",
    watermark: "#d4d4d4",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 48,
    cardPaddingY: 48,
    cardRadius: 4,
    cardBorder: "none",
    cardShadow: "0 2px 8px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 4. Kenya Hara ────────────────────────────────────────────
  {
    id: "kenya-hara",
    name: "原研哉·白",
    nameEn: "Kenya Hara",
    description: "极致留白，东方禅意",
    tags: ["极简", "设计"],
    mode: "light",
    titleFont: "'Noto Sans SC', 'Helvetica Neue', sans-serif",
    bodyFont: "'Noto Sans SC', 'Helvetica Neue', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 20,
    titleFontWeight: 300,
    titleLineHeight: 1.6,
    titleLetterSpacing: "0.15em",
    titleAlign: "left",
    bodyFontSize: 14,
    bodyLineHeight: 2.2,
    bodyLetterSpacing: "0.05em",
    background: "#fefefe",
    cardBg: "transparent",
    textColor: "#333333",
    secondaryText: "#999999",
    accent: "#888888",
    codeBg: "#f8f8f8",
    quoteBorder: "#dddddd",
    calloutBg: "#fafafa",
    tableBorder: "#eeeeee",
    divider: "#eeeeee",
    watermark: "#cccccc",
    containerPaddingX: 80,
    containerPaddingY: 80,
    cardPaddingX: 0,
    cardPaddingY: 0,
    cardRadius: 0,
    cardBorder: "none",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: false,
  },

  // ── 5. Typewriter ────────────────────────────────────────────
  {
    id: "typewriter",
    name: "复古打字机",
    nameEn: "Typewriter",
    description: "米黄纸张，文学气息",
    tags: ["复古", "文学"],
    mode: "light",
    titleFont: "'Courier Prime', 'FangSong', 'STFangsong', serif",
    bodyFont: "'Courier Prime', 'FangSong', 'STFangsong', serif",
    codeFont: "'Courier Prime', monospace",
    titleFontSize: 24,
    titleFontWeight: 700,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.85,
    bodyLetterSpacing: "0.01em",
    background: "#f5f0e6",
    cardBg: "#faf6ed",
    textColor: "#3d3225",
    secondaryText: "#8a7e6b",
    accent: "#8b4513",
    codeBg: "#f0ebe0",
    quoteBorder: "#d4c9b8",
    calloutBg: "#f5f0e4",
    tableBorder: "#d4c9b8",
    divider: "#d4c9b8",
    watermark: "#d8cfc4",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 40,
    cardRadius: 2,
    cardBorder: "1px solid #e8e0d0",
    cardShadow: "0 1px 4px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04), inset 0 0 60px rgba(139,69,19,0.02)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 6. Neon ──────────────────────────────────────────────────
  {
    id: "neon",
    name: "霓虹渐变",
    nameEn: "Neon",
    description: "鲜艳渐变，视觉冲击",
    tags: ["渐变", "社交"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 36,
    titleFontWeight: 800,
    titleLineHeight: 1.15,
    titleLetterSpacing: "-0.02em",
    titleAlign: "center",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 30%, #f093fb 70%, #f5576c 100%)",
    cardBg: "rgba(255,255,255,0.97)",
    textColor: "#1a1a2e",
    secondaryText: "#6b7280",
    accent: "#7c3aed",
    codeBg: "#f5f3ff",
    quoteBorder: "#ddd6fe",
    calloutBg: "#faf5ff",
    tableBorder: "#e9d5ff",
    divider: "#e9d5ff",
    watermark: "#c4b5fd",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 44,
    cardPaddingY: 40,
    cardRadius: 24,
    cardBorder: "1px solid rgba(255,255,255,0.5)",
    cardShadow: "0 20px 60px rgba(0,0,0,0.15), 0 0 0 1px rgba(255,255,255,0.3)",
    showDecorations: true,
    decorationColor: "rgba(124,58,237,0.08)",
    watermarkVisible: true,
  },

  // ── 7. Academic ──────────────────────────────────────────────
  {
    id: "academic",
    name: "学术 LaTeX",
    nameEn: "Academic",
    description: "严谨排版，论文感",
    tags: ["学术", "严肃"],
    mode: "light",
    titleFont: "'Latin Modern Roman', 'Noto Serif SC', 'Times New Roman', serif",
    bodyFont: "'Latin Modern Roman', 'Noto Serif SC', 'Times New Roman', serif",
    codeFont: "'Latin Modern Mono', 'JetBrains Mono', monospace",
    titleFontSize: 22,
    titleFontWeight: 700,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0",
    titleAlign: "center",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#000000",
    secondaryText: "#555555",
    accent: "#0066cc",
    codeBg: "#f8f8f8",
    quoteBorder: "#cccccc",
    calloutBg: "#fafafa",
    tableBorder: "#cccccc",
    divider: "#cccccc",
    watermark: "#bbbbbb",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 48,
    cardPaddingY: 40,
    cardRadius: 0,
    cardBorder: "1px solid #e0e0e0",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 8. Stationery ────────────────────────────────────────────
  {
    id: "stationery",
    name: "手账便签",
    nameEn: "Stationery",
    description: "温暖手写，生活气息",
    tags: ["手写", "温馨"],
    mode: "light",
    titleFont: "'ZCOOL XiaoWei', 'Ma Shan Zheng', 'Noto Sans SC', cursive",
    bodyFont: "'ZCOOL XiaoWei', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 400,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0.04em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.85,
    bodyLetterSpacing: "0.02em",
    background: "#fef9e7",
    cardBg: "#fffef5",
    textColor: "#4a4035",
    secondaryText: "#9a8e7e",
    accent: "#d97706",
    codeBg: "#faf5e6",
    quoteBorder: "#e8dcc8",
    calloutBg: "#fdf8ed",
    tableBorder: "#e8dcc8",
    divider: "#e8dcc8",
    watermark: "#ddd5c8",
    containerPaddingX: 52,
    containerPaddingY: 52,
    cardPaddingX: 36,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #f0e8d0",
    cardShadow: "0 2px 8px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.03), inset 0 1px 0 rgba(255,255,255,0.8)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 9. Poster ────────────────────────────────────────────────
  {
    id: "poster",
    name: "海报大字报",
    nameEn: "Poster",
    description: "冲击力强，短内容",
    tags: ["海报", "冲击"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 42,
    titleFontWeight: 900,
    titleLineHeight: 1.1,
    titleLetterSpacing: "-0.03em",
    titleAlign: "center",
    bodyFontSize: 16,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "linear-gradient(145deg, #1a1a2e 0%, #16213e 40%, #0f3460 100%)",
    cardBg: "transparent",
    textColor: "#ffffff",
    secondaryText: "rgba(255,255,255,0.7)",
    accent: "#00d9ff",
    codeBg: "rgba(255,255,255,0.08)",
    quoteBorder: "rgba(255,255,255,0.2)",
    calloutBg: "rgba(255,255,255,0.05)",
    tableBorder: "rgba(255,255,255,0.15)",
    divider: "rgba(255,255,255,0.15)",
    watermark: "rgba(255,255,255,0.22)",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 40,
    cardRadius: 0,
    cardBorder: "none",
    cardShadow: "none",
    showDecorations: true,
    decorationColor: "rgba(0,217,255,0.1)",
    watermarkVisible: true,
  },

  // ── 10. GitHub Light ─────────────────────────────────────────
  {
    id: "github-light",
    name: "GitHub 浅",
    nameEn: "GitHub Light",
    description: "GitHub 官方浅色，开发者友好",
    tags: ["浅色", "开发"],
    mode: "light",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#1f2328",
    secondaryText: "#59636e",
    accent: "#0969da",
    codeBg: "#f6f8fa",
    quoteBorder: "#d1d9e0",
    calloutBg: "#f6f8fa",
    tableBorder: "#d1d9e0",
    divider: "#d1d9e0",
    watermark: "#8b949e",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #d1d9e0",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 11. GitHub Dark ──────────────────────────────────────────
  {
    id: "github-dark",
    name: "GitHub 深",
    nameEn: "GitHub Dark",
    description: "GitHub 官方深色，平静专注",
    tags: ["深色", "开发"],
    mode: "dark",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#0d1117",
    cardBg: "#0d1117",
    textColor: "#e6edf3",
    secondaryText: "#8b949e",
    accent: "#2f81f7",
    codeBg: "#161b22",
    quoteBorder: "#30363d",
    calloutBg: "#161b22",
    tableBorder: "#30363d",
    divider: "#21262d",
    watermark: "#6e7681",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #30363d",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 12. Vercel Geist ─────────────────────────────────────────
  {
    id: "vercel-dark",
    name: "Vercel 极黑",
    nameEn: "Vercel Geist",
    description: "纯黑极简，硬核现代",
    tags: ["深色", "极简"],
    mode: "dark",
    titleFont: "'Geist', 'Inter', -apple-system, sans-serif",
    bodyFont: "'Geist', 'Inter', -apple-system, sans-serif",
    codeFont: "'Geist Mono', 'JetBrains Mono', monospace",
    titleFontSize: 34,
    titleFontWeight: 600,
    titleLineHeight: 1.15,
    titleLetterSpacing: "-0.03em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "-0.005em",
    background: "#0a0a0a",
    cardBg: "#0a0a0a",
    textColor: "#ededed",
    secondaryText: "#a1a1aa",
    accent: "#ffffff",
    codeBg: "#171717",
    quoteBorder: "#262626",
    calloutBg: "#141414",
    tableBorder: "#262626",
    divider: "#1f1f1f",
    watermark: "#52525b",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 44,
    cardPaddingY: 44,
    cardRadius: 0,
    cardBorder: "1px solid #262626",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 13. Tokyo Night ──────────────────────────────────────────
  {
    id: "tokyo-night",
    name: "东京之夜",
    nameEn: "Tokyo Night",
    description: "深蓝紫调，编辑器经典",
    tags: ["深色", "代码"],
    mode: "dark",
    titleFont: "'Inter', 'JetBrains Mono', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "linear-gradient(155deg, #1a1b26 0%, #1f2335 100%)",
    cardBg: "#24283b",
    textColor: "#c0caf5",
    secondaryText: "#9aa5ce",
    accent: "#7aa2f7",
    codeBg: "#1f2335",
    quoteBorder: "#414868",
    calloutBg: "#292e42",
    tableBorder: "#414868",
    divider: "#292e42",
    watermark: "#565f89",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 38,
    cardRadius: 14,
    cardBorder: "1px solid #292e42",
    cardShadow: "0 12px 36px rgba(0,0,0,0.45), inset 0 0 0 1px rgba(255,255,255,0.02)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 14. Catppuccin Macchiato ─────────────────────────────────
  {
    id: "catppuccin",
    name: "Catppuccin",
    nameEn: "Macchiato",
    description: "柔和粉调暗色，开发者最爱",
    tags: ["深色", "柔和"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "#24273a",
    cardBg: "#1e2030",
    textColor: "#cad3f5",
    secondaryText: "#a5adcb",
    accent: "#c6a0f6",
    codeBg: "#181926",
    quoteBorder: "#494d64",
    calloutBg: "#363a4f",
    tableBorder: "#494d64",
    divider: "#363a4f",
    watermark: "#6e738d",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 14,
    cardBorder: "1px solid #363a4f",
    cardShadow: "0 10px 30px rgba(0,0,0,0.35)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 15. Synthwave ────────────────────────────────────────────
  {
    id: "synthwave",
    name: "蒸汽合成",
    nameEn: "Synthwave",
    description: "复古赛博朋克，霓虹回潮",
    tags: ["深色", "复古"],
    mode: "dark",
    titleFont: "'Space Grotesk', 'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 32,
    titleFontWeight: 700,
    titleLineHeight: 1.15,
    titleLetterSpacing: "-0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "linear-gradient(165deg, #1a0533 0%, #2d0a4e 45%, #0d0220 100%)",
    cardBg: "rgba(20,8,40,0.6)",
    textColor: "#f8f8f2",
    secondaryText: "#bfa3d9",
    accent: "#ff2a6d",
    codeBg: "rgba(0,0,0,0.4)",
    quoteBorder: "#ff2a6d",
    calloutBg: "rgba(255,42,109,0.08)",
    tableBorder: "rgba(255,255,255,0.12)",
    divider: "rgba(255,255,255,0.08)",
    watermark: "rgba(255,42,109,0.45)",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 18,
    cardBorder: "1px solid rgba(255,42,109,0.25)",
    cardShadow: "0 0 50px rgba(255,42,109,0.18), inset 0 0 0 1px rgba(255,255,255,0.04)",
    showDecorations: true,
    decorationColor: "rgba(0,217,255,0.12)",
    watermarkVisible: true,
  },

  // ── 16. Linear ───────────────────────────────────────────────
  {
    id: "linear",
    name: "Linear",
    nameEn: "Linear",
    description: "几何冷感，工程师审美",
    tags: ["浅色", "几何"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 30,
    titleFontWeight: 600,
    titleLineHeight: 1.2,
    titleLetterSpacing: "-0.025em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "-0.005em",
    background: "linear-gradient(180deg, #ffffff 0%, #fafbfc 100%)",
    cardBg: "#ffffff",
    textColor: "#1c1d22",
    secondaryText: "#6e7079",
    accent: "#5e6ad2",
    codeBg: "#f7f8fa",
    quoteBorder: "#ebebee",
    calloutBg: "#f7f8fa",
    tableBorder: "#ebebee",
    divider: "#ebebee",
    watermark: "#b8b8c0",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 14,
    cardBorder: "1px solid #ebebee",
    cardShadow: "0 1px 2px rgba(0,0,0,0.04), 0 10px 30px rgba(0,0,0,0.04)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 17. Mocha Mousse (Pantone-inspired) ──────────────────────
  {
    id: "mocha-mousse",
    name: "摩卡慕斯",
    nameEn: "Mocha Mousse",
    description: "暖棕大地色，2025 年度风",
    tags: ["浅色", "温暖"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 30,
    titleFontWeight: 500,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#f5ede0",
    cardBg: "#fdf8ee",
    textColor: "#3d2f24",
    secondaryText: "#8a7560",
    accent: "#a47864",
    codeBg: "#ede3d3",
    quoteBorder: "#c9b8a3",
    calloutBg: "#f5ede0",
    tableBorder: "#d8c8b3",
    divider: "#e5d8c4",
    watermark: "#b8a690",
    containerPaddingX: 60,
    containerPaddingY: 60,
    cardPaddingX: 44,
    cardPaddingY: 42,
    cardRadius: 18,
    cardBorder: "none",
    cardShadow: "0 4px 24px rgba(164,120,100,0.1), 0 1px 2px rgba(164,120,100,0.06)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 18. Solarized Light ──────────────────────────────────────
  {
    id: "solarized-light",
    name: "Solarized 浅",
    nameEn: "Solarized",
    description: "经典护眼配色，米黄沉静",
    tags: ["浅色", "经典"],
    mode: "light",
    titleFont: "'Inter', 'IBM Plex Sans', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'IBM Plex Mono', monospace",
    titleFontSize: 27,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "#fdf6e3",
    cardBg: "#fdf6e3",
    textColor: "#586e75",
    secondaryText: "#93a1a1",
    accent: "#268bd2",
    codeBg: "#eee8d5",
    quoteBorder: "#93a1a1",
    calloutBg: "#eee8d5",
    tableBorder: "#d8d2bf",
    divider: "#eee8d5",
    watermark: "#a8a08a",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 8,
    cardBorder: "1px solid #eee8d5",
    cardShadow: "0 1px 3px rgba(88,110,117,0.06), 0 4px 16px rgba(88,110,117,0.04)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 19. Brutalist ────────────────────────────────────────────
  {
    id: "brutalist",
    name: "野性印刷",
    nameEn: "Brutalist",
    description: "硬边大字 + 实心投影，叛逆派",
    tags: ["浅色", "特立独行"],
    mode: "light",
    titleFont: "'Space Grotesk', 'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 42,
    titleFontWeight: 800,
    titleLineHeight: 1.02,
    titleLetterSpacing: "-0.04em",
    titleAlign: "left",
    bodyFontSize: 16,
    bodyLineHeight: 1.6,
    bodyLetterSpacing: "0",
    background: "#f5f5f5",
    cardBg: "#ffffff",
    textColor: "#0a0a0a",
    secondaryText: "#525252",
    accent: "#ff5500",
    codeBg: "#0a0a0a",
    codeTextColor: "#fafafa",
    quoteBorder: "#0a0a0a",
    calloutBg: "#ffe4d6",
    tableBorder: "#0a0a0a",
    divider: "#0a0a0a",
    watermark: "#a3a3a3",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 0,
    cardBorder: "2px solid #0a0a0a",
    cardShadow: "6px 6px 0 #0a0a0a",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 20. Risograph ────────────────────────────────────────────
  {
    id: "risograph",
    name: "Risograph",
    nameEn: "Risograph",
    description: "孔版印刷，荧光油墨手感",
    tags: ["浅色", "印刷"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#faf5ec",
    cardBg: "#fffaf0",
    textColor: "#2c2825",
    secondaryText: "#8a7d6e",
    accent: "#f06f6f",
    codeBg: "#f5ede0",
    quoteBorder: "#d4c5a8",
    calloutBg: "#fdf2e0",
    tableBorder: "#d4c5a8",
    divider: "#e5d8c4",
    watermark: "#b8a690",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 4,
    cardBorder: "1px solid #d4c5a8",
    cardShadow: "4px 4px 0 rgba(240,111,111,0.18)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },
];

export type CardThemeId = (typeof CARD_THEMES)[number]["id"];

export function getCardTheme(themeId: CardThemeId): CardTheme {
  return CARD_THEMES.find((t) => t.id === themeId) ?? CARD_THEMES[0];
}
