import { TEXT_COLORS } from "@/lib/textColors";
import type { CardTheme } from "../types";

export const ARTISTIC_EXPRESSIVE: CardTheme[] = [
  // ── 8. Stationery ────────────────────────────────────────────
  {
    id: "stationery",
    name: "手账便签",
    nameEn: "Stationery",
    description: "温暖手写，生活气息",
    tags: ["手写", "温馨"],
    mode: "light",
    titleFont: "'Ma Shan Zheng', 'ZCOOL XiaoWei', 'Noto Sans SC', 'PingFang SC', sans-serif",
    bodyFont: "'Noto Sans SC', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 400,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0.04em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.85,
    bodyLetterSpacing: "0.02em",
    background: "#fef9e7",
    cardBg: "#fffef5",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#d97706",
    codeBg: "#faf5e6",
    quoteBorder: "#e8dcc8",
    calloutBg: "#fdf8ed",
    tableBorder: "#e8dcc8",
    divider: "#e8dcc8",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 52,
    containerPaddingY: 52,
    cardPaddingX: 36,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #f0e8d0",
    cardShadow: "0 2px 8px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.03), inset 0 1px 0 rgba(255,255,255,0.8)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 17. Mocha Mousse (Pantone-inspired) ──────────────────────
  {
    id: "mocha-mousse",
    name: "摩卡慕斯",
    nameEn: "Mocha Mousse",
    description: "暖棕大地色，2025 年度风",
    tags: ["浅色", "温暖"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 30,
    titleFontWeight: 500,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#f5ede0",
    cardBg: "#fdf8ee",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#a47864",
    codeBg: "#ede3d3",
    quoteBorder: "#c9b8a3",
    calloutBg: "#f5ede0",
    tableBorder: "#d8c8b3",
    divider: "#e5d8c4",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 60,
    containerPaddingY: 60,
    cardPaddingX: 44,
    cardPaddingY: 42,
    cardRadius: 18,
    cardBorder: "none",
    cardShadow: "0 4px 24px rgba(164,120,100,0.1), 0 1px 2px rgba(164,120,100,0.06)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 19. Brutalist ────────────────────────────────────────────
  {
    id: "brutalist",
    name: "野性印刷",
    nameEn: "Brutalist",
    description: "硬边大字 + 实心投影，叛逆派",
    tags: ["浅色", "特立独行"],
    mode: "light",
    titleFont: "'Space Grotesk', 'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 42,
    titleFontWeight: 700,
    titleLineHeight: 1.02,
    titleLetterSpacing: "-0.04em",
    titleAlign: "left",
    bodyFontSize: 16,
    bodyLineHeight: 1.6,
    bodyLetterSpacing: "0",
    background: "#f5f5f5",
    cardBg: "#ffffff",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#ff5500",
    codeBg: "#0a0a0a",
    codeTextColor: TEXT_COLORS.dark.primary,
    quoteBorder: "#0a0a0a",
    calloutBg: "#ffe4d6",
    tableBorder: "#0a0a0a",
    divider: "#0a0a0a",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 0,
    cardBorder: "2px solid #0a0a0a",
    cardShadow: "6px 6px 0 #0a0a0a",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 20. Risograph ────────────────────────────────────────────
  {
    id: "risograph",
    name: "Risograph",
    nameEn: "Risograph",
    description: "孔版印刷，荧光油墨手感",
    tags: ["浅色", "印刷"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#faf5ec",
    cardBg: "#fffaf0",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#f06f6f",
    codeBg: "#f5ede0",
    quoteBorder: "#d4c5a8",
    calloutBg: "#fdf2e0",
    tableBorder: "#d4c5a8",
    divider: "#e5d8c4",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 4,
    cardBorder: "1px solid #d4c5a8",
    cardShadow: "4px 4px 0 rgba(240,111,111,0.18)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },
];
