import { TEXT_COLORS } from "@/lib/textColors";
import type { CardTheme } from "../types";

export const TECH_DOCUMENT: CardTheme[] = [
  // ── 1. Notion ────────────────────────────────────────────────
  {
    id: "notion",
    name: "极简白",
    nameEn: "Minimal White",
    description: "极简专业，文档感",
    tags: ["极简", "文档"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 700,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#2d6cdf",
    codeBg: "#f5f5f5",
    quoteBorder: "#e5e7eb",
    calloutBg: "#f9fafb",
    tableBorder: "#e5e7eb",
    divider: "#e5e7eb",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #f0f0f0",
    cardShadow: "0 1px 3px rgba(0,0,0,0.02), 0 4px 12px rgba(0,0,0,0.03)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 2. Obsidian ──────────────────────────────────────────────
  {
    id: "obsidian",
    name: "深邃夜",
    nameEn: "Deep Night",
    description: "深色模式，代码感",
    tags: ["深色", "技术"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 700,
    titleLineHeight: 1.35,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "linear-gradient(160deg, #0d1117 0%, #161b22 50%, #0d1117 100%)",
    cardBg: "#161b22",
    textColor: TEXT_COLORS.dark.primary,
    secondaryText: TEXT_COLORS.dark.secondary,
    accent: "#58a6ff",
    codeBg: "#0d1117",
    quoteBorder: "#30363d",
    calloutBg: "#21262d",
    tableBorder: "#30363d",
    divider: "#30363d",
    watermark: TEXT_COLORS.dark.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #30363d",
    cardShadow: "0 8px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.03)",
    showDecorations: true,
    decorationColor: "rgba(88,166,255,0.06)",
    watermarkVisible: true,
  },

  // ── 10. GitHub Light ─────────────────────────────────────────
  {
    id: "github-light",
    name: "GitHub 浅",
    nameEn: "GitHub Light",
    description: "GitHub 官方浅色，开发者友好",
    tags: ["浅色", "开发"],
    mode: "light",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: TEXT_COLORS.light.primary,
    secondaryText: TEXT_COLORS.light.secondary,
    accent: "#0969da",
    codeBg: "#f6f8fa",
    quoteBorder: "#d1d9e0",
    calloutBg: "#f6f8fa",
    tableBorder: "#d1d9e0",
    divider: "#d1d9e0",
    watermark: TEXT_COLORS.light.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #d1d9e0",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 11. GitHub Dark ──────────────────────────────────────────
  {
    id: "github-dark",
    name: "GitHub 深",
    nameEn: "GitHub Dark",
    description: "GitHub 官方深色，平静专注",
    tags: ["深色", "开发"],
    mode: "dark",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#0d1117",
    cardBg: "#0d1117",
    textColor: TEXT_COLORS.dark.primary,
    secondaryText: TEXT_COLORS.dark.secondary,
    accent: "#2f81f7",
    codeBg: "#161b22",
    quoteBorder: "#30363d",
    calloutBg: "#161b22",
    tableBorder: "#30363d",
    divider: "#21262d",
    watermark: TEXT_COLORS.dark.secondary,
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #30363d",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

];
