export const POPULAR_LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "csharp",
  "php",
  "ruby",
  "go",
  "rust",
  "swift",
  "kotlin",
  "cpp",
  "c",
  "html",
  "css",
  "scss",
  "json",
  "yaml",
  "xml",
  "markdown",
  "sql",
  "bash",
  "shell",
  "powershell",
  "docker",
  "nginx",
  "graphql",
  "vue",
  "jsx",
  "tsx",
  "svelte",
  "toml",
  "ini",
  "makefile",
  "cmake",
  "diff",
  "lua",
  "dart",
  "solidity",
  "latex",
  "bat",
  "applescript",
  "r",
  "julia",
  "scala",
  "elixir",
  "haskell",
  "protobuf",
  "lisp",
  "clojure",
  "fortran",
  "erlang",
  "perl",
  "objectc",
  "vim",
  "wasm",
];

export const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  python: "Python",
  java: "Java",
  csharp: "C#",
  php: "PHP",
  ruby: "Ruby",
  go: "Go",
  rust: "Rust",
  swift: "Swift",
  kotlin: "Kotlin",
  cpp: "C++",
  c: "C",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  json: "JSON",
  yaml: "YAML",
  xml: "XML",
  markdown: "Markdown",
  md: "Markdown",
  sql: "SQL",
  bash: "Bash",
  shell: "Shell",
  powershell: "PowerShell",
  docker: "Dockerfile",
  nginx: "Nginx",
  graphql: "GraphQL",
  vue: "Vue",
  jsx: "JSX",
  tsx: "TSX",
  svelte: "Svelte",
  toml: "TOML",
  ini: "INI",
  makefile: "Makefile",
  cmake: "CMake",
  diff: "Diff",
  lua: "Lua",
  dart: "Dart",
  solidity: "Solidity",
  latex: "LaTeX",
  bat: "Batch",
  applescript: "AppleScript",
  r: "R",
  julia: "Julia",
  scala: "Scala",
  elixir: "Elixir",
  haskell: "Haskell",
  protobuf: "Protobuf",
  lisp: "Lisp",
  clojure: "Clojure",
  fortran: "Fortran",
  erlang: "Erlang",
  perl: "Perl",
  objectc: "Objective-C",
  vim: "Vim Script",
  wasm: "WebAssembly",
  math: "数学公式 ($$)",
  "yaml-frontmatter": "文档元数据 (YAML)",
  text: "Plain Text",
};

export const FORMAT_SUPPORTED_LANGUAGES = [
  "javascript",
  "js",
  "jsx",
  "typescript",
  "ts",
  "tsx",
  "json",
  "css",
  "scss",
  "less",
  "html",
  "markdown",
  "md",
];
