/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Button: typeof import('./components/ui/button').Button
  const CREATOR_FLOW_CONTENT: typeof import('./lib/onboarding').CREATOR_FLOW_CONTENT
  const Card: typeof import('./components/ui/card').Card
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const Check: typeof import('lucide-react').Check
  const ChevronDown: typeof import('lucide-react').ChevronDown
  const ChevronRight: typeof import('lucide-react').ChevronRight
  const Code: typeof import('lucide-react').Code
  const ContextMenu: typeof import('./components/ui/context-menu').ContextMenu
  const ContextMenuCheckboxItem: typeof import('./components/ui/context-menu').ContextMenuCheckboxItem
  const ContextMenuContent: typeof import('./components/ui/context-menu').ContextMenuContent
  const ContextMenuGroup: typeof import('./components/ui/context-menu').ContextMenuGroup
  const ContextMenuItem: typeof import('./components/ui/context-menu').ContextMenuItem
  const ContextMenuLabel: typeof import('./components/ui/context-menu').ContextMenuLabel
  const ContextMenuPortal: typeof import('./components/ui/context-menu').ContextMenuPortal
  const ContextMenuRadioGroup: typeof import('./components/ui/context-menu').ContextMenuRadioGroup
  const ContextMenuRadioItem: typeof import('./components/ui/context-menu').ContextMenuRadioItem
  const ContextMenuSeparator: typeof import('./components/ui/context-menu').ContextMenuSeparator
  const ContextMenuShortcut: typeof import('./components/ui/context-menu').ContextMenuShortcut
  const ContextMenuSub: typeof import('./components/ui/context-menu').ContextMenuSub
  const ContextMenuSubContent: typeof import('./components/ui/context-menu').ContextMenuSubContent
  const ContextMenuSubTrigger: typeof import('./components/ui/context-menu').ContextMenuSubTrigger
  const ContextMenuTrigger: typeof import('./components/ui/context-menu').ContextMenuTrigger
  const DEFAULT_NOTEBOOK: typeof import('./stores/useNotebooks').DEFAULT_NOTEBOOK
  const DEFAULT_SEARCH_PROVIDERS: typeof import('./stores/useSettings').DEFAULT_SEARCH_PROVIDERS
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const ECOMMERCE_DATA_CONTENT: typeof import('./lib/onboarding').ECOMMERCE_DATA_CONTENT
  const EDITOR_FONT_SIZE_DEFAULT: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_DEFAULT
  const EDITOR_FONT_SIZE_MAX: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_MAX
  const EDITOR_FONT_SIZE_MIN: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_MIN
  const FileText: typeof import('lucide-react').FileText
  const Fragment: typeof import('react').Fragment
  const HighlightText: typeof import('./lib/highlight-text').HighlightText
  const Image: typeof import('lucide-react').Image
  const Input: typeof import('./components/ui/input').Input
  const Label: typeof import('./components/ui/label').Label
  const Link: typeof import('lucide-react').Link
  const List: typeof import('lucide-react').List
  const ListOrdered: typeof import('lucide-react').ListOrdered
  const LucideIcons: typeof import('lucide-react')
  const Menu: typeof import('lucide-react').Menu
  const MoreHorizontal: typeof import('lucide-react').MoreHorizontal
  const ONBOARDING_CHILD_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_CHILD_PAGE_CONTENT
  const ONBOARDING_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_PAGE_CONTENT
  const ONBOARDING_STEPS: typeof import('./stores/useOnboardingGuide').ONBOARDING_STEPS
  const Plus: typeof import('lucide-react').Plus
  const Popover: typeof import('./components/ui/popover').Popover
  const PopoverContent: typeof import('./components/ui/popover').PopoverContent
  const PopoverTrigger: typeof import('./components/ui/popover').PopoverTrigger
  const ScrollArea: typeof import('./components/ui/scroll-area').ScrollArea
  const ScrollBar: typeof import('./components/ui/scroll-area').ScrollBar
  const Search: typeof import('lucide-react').Search
  const Separator: typeof import('./components/ui/separator').Separator
  const Settings: typeof import('lucide-react').Settings
  const Sheet: typeof import('./components/ui/sheet').Sheet
  const SheetClose: typeof import('./components/ui/sheet').SheetClose
  const SheetContent: typeof import('./components/ui/sheet').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet').SheetHeader
  const SheetOverlay: typeof import('./components/ui/sheet').SheetOverlay
  const SheetPortal: typeof import('./components/ui/sheet').SheetPortal
  const SheetTitle: typeof import('./components/ui/sheet').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet').SheetTrigger
  const Slider: typeof import('./components/ui/slider').Slider
  const Suspense: typeof import('react').Suspense
  const Switch: typeof import('./components/ui/switch').Switch
  const TIPS: typeof import('./lib/tips').TIPS
  const Tabs: typeof import('./components/ui/tabs').Tabs
  const TabsContent: typeof import('./components/ui/tabs').TabsContent
  const TabsList: typeof import('./components/ui/tabs').TabsList
  const TabsTrigger: typeof import('./components/ui/tabs').TabsTrigger
  const Textarea: typeof import('./components/ui/textarea').Textarea
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const Toggle: typeof import('./components/ui/toggle').Toggle
  const Tooltip: typeof import('./components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip').TooltipTrigger
  const Trash2: typeof import('lucide-react').Trash2
  const UToolsAdapter: typeof import('./lib/utools').UToolsAdapter
  const WINDOW_HEIGHT_DEFAULT: typeof import('./stores/useSettings').WINDOW_HEIGHT_DEFAULT
  const WINDOW_HEIGHT_MAX: typeof import('./stores/useSettings').WINDOW_HEIGHT_MAX
  const WINDOW_HEIGHT_MIN: typeof import('./stores/useSettings').WINDOW_HEIGHT_MIN
  const X: typeof import('lucide-react').X
  const applyFontVariables: typeof import('./lib/fontLoader').applyFontVariables
  const blobToBase64: typeof import('./lib/imageProcessor').blobToBase64
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const clsx: typeof import('clsx').clsx
  const cn: typeof import('./lib/utils').cn
  const compressImage: typeof import('./lib/imageProcessor').compressImage
  const containsMarkdownTable: typeof import('./lib/markdownTableParser').containsMarkdownTable
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const exportNotebooks: typeof import('./lib/export').exportNotebooks
  const exportToHTML: typeof import('./lib/export').exportToHTML
  const exportToJSON: typeof import('./lib/export').exportToJSON
  const exportToMarkdown: typeof import('./lib/export').exportToMarkdown
  const extractTextFromContent: typeof import('./lib/content-text-extractor').extractTextFromContent
  const extractTitleFromContent: typeof import('./lib/content-text-extractor').extractTitleFromContent
  const flushEditorContent: typeof import('./stores/usePages').flushEditorContent
  const formatShortcut: typeof import('./lib/utils').formatShortcut
  const forwardRef: typeof import('react').forwardRef
  const getEditorFontFamilies: typeof import('./lib/fontLoader').getEditorFontFamilies
  const getFontFamiliesToLoad: typeof import('./lib/fontLoader').getFontFamiliesToLoad
  const getImageFromClipboard: typeof import('./lib/imageProcessor').getImageFromClipboard
  const getPageTitle: typeof import('./lib/page-title').getPageTitle
  const getRandomTip: typeof import('./lib/tips').getRandomTip
  const importFile: typeof import('./lib/export').importFile
  const importFromJSON: typeof import('./lib/export').importFromJSON
  const importFromMarkdown: typeof import('./lib/export').importFromMarkdown
  const importNotebooksFromZip: typeof import('./lib/export').importNotebooksFromZip
  const isValidImageUrl: typeof import('./lib/imageProcessor').isValidImageUrl
  const jsonContentToMarkdown: typeof import('./lib/export').jsonContentToMarkdown
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const parseMarkdownTableToHtml: typeof import('./lib/markdownTableParser').parseMarkdownTableToHtml
  const parseMarkdownToHtml: typeof import('./lib/markdownTableParser').parseMarkdownToHtml
  const preloadFonts: typeof import('./lib/fontLoader').preloadFonts
  const processImageForStorage: typeof import('./lib/imageProcessor').processImageForStorage
  const startTransition: typeof import('react').startTransition
  const toggleVariants: typeof import('./components/ui/toggle').toggleVariants
  const uToolsStorage: typeof import('./lib/storage').uToolsStorage
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useContextMenu: typeof import('./stores/useContextMenu').useContextMenu
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeletePageWithUndo: typeof import('./hooks/useDeletePageWithUndo').useDeletePageWithUndo
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormatCode: typeof import('./hooks/useFormatCode').useFormatCode
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useNotebooks: typeof import('./stores/useNotebooks').useNotebooks
  const useOnboardingGuide: typeof import('./stores/useOnboardingGuide').useOnboardingGuide
  const useOptimistic: typeof import('react').useOptimistic
  const usePages: typeof import('./stores/usePages').usePages
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useScrollHide: typeof import('./hooks/useScrollHide').useScrollHide
  const useSettings: typeof import('./stores/useSettings').useSettings
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const waitForFonts: typeof import('./lib/fontLoader').waitForFonts
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Notebook } from './stores/useNotebooks'
  import('./stores/useNotebooks')
  // @ts-ignore
  export type { SearchProvider, Theme, CodeStyle, UToolsSettings, FontConfig, CustomFonts, UIFontSize } from './stores/useSettings'
  import('./stores/useSettings')
  // @ts-ignore
  export type { ExportOptions, ImportResult } from './lib/export'
  import('./lib/export')
  // @ts-ignore
  export type { UToolsAdapter, UserInfo, SublistItem } from './lib/utools'
  import('./lib/utools')
  // @ts-ignore
  export type { ButtonProps } from './components/ui/button'
  import('./components/ui/button')
}
