/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AiGradientIcon: typeof import('./components/ui/ai-gradient-icon').AiGradientIcon
  const BLOCK_BG_COLORS: typeof import('./lib/blockColorPresets').BLOCK_BG_COLORS
  const Button: typeof import('./components/ui/button').Button
  const CARD_THEMES: typeof import('./lib/imageExport/index').CARD_THEMES
  const Card: typeof import('./components/ui/card').Card
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const ContextMenu: typeof import('./components/ui/context-menu').ContextMenu
  const ContextMenuCheckboxItem: typeof import('./components/ui/context-menu').ContextMenuCheckboxItem
  const ContextMenuContent: typeof import('./components/ui/context-menu').ContextMenuContent
  const ContextMenuGroup: typeof import('./components/ui/context-menu').ContextMenuGroup
  const ContextMenuItem: typeof import('./components/ui/context-menu').ContextMenuItem
  const ContextMenuLabel: typeof import('./components/ui/context-menu').ContextMenuLabel
  const ContextMenuPortal: typeof import('./components/ui/context-menu').ContextMenuPortal
  const ContextMenuRadioGroup: typeof import('./components/ui/context-menu').ContextMenuRadioGroup
  const ContextMenuRadioItem: typeof import('./components/ui/context-menu').ContextMenuRadioItem
  const ContextMenuSeparator: typeof import('./components/ui/context-menu').ContextMenuSeparator
  const ContextMenuShortcut: typeof import('./components/ui/context-menu').ContextMenuShortcut
  const ContextMenuSub: typeof import('./components/ui/context-menu').ContextMenuSub
  const ContextMenuSubContent: typeof import('./components/ui/context-menu').ContextMenuSubContent
  const ContextMenuSubTrigger: typeof import('./components/ui/context-menu').ContextMenuSubTrigger
  const ContextMenuTrigger: typeof import('./components/ui/context-menu').ContextMenuTrigger
  const DEFAULT_CLAUDE_BASE_URL: typeof import('./lib/ai-provider').DEFAULT_CLAUDE_BASE_URL
  const DEFAULT_CLOSE_TAB_SHORTCUT: typeof import('./stores/useSettings').DEFAULT_CLOSE_TAB_SHORTCUT
  const DEFAULT_NOTEBOOK: typeof import('./stores/useNotebooks').DEFAULT_NOTEBOOK
  const DEFAULT_OPENAI_BASE_URL: typeof import('./lib/ai-provider').DEFAULT_OPENAI_BASE_URL
  const DEFAULT_SEARCH_HOTKEY: typeof import('./stores/useSettings').DEFAULT_SEARCH_HOTKEY
  const DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT: typeof import('./stores/useSettings').DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT
  const DEFAULT_SEARCH_PROVIDERS: typeof import('./stores/useSettings').DEFAULT_SEARCH_PROVIDERS
  const DEFAULT_WAKE_HOTKEY: typeof import('./stores/useSettings').DEFAULT_WAKE_HOTKEY
  const DEFAULT_WATERMARK_CONFIG: typeof import('./lib/imageExport/index').DEFAULT_WATERMARK_CONFIG
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogShell: typeof import('./components/ui/dialog-shell').DialogShell
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const EDITOR_FONT_SIZE_DEFAULT: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_DEFAULT
  const EDITOR_FONT_SIZE_MAX: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_MAX
  const EDITOR_FONT_SIZE_MIN: typeof import('./stores/useSettings').EDITOR_FONT_SIZE_MIN
  const FeatureToastCard: typeof import('./components/ui/feature-toast-card').FeatureToastCard
  const FileTrigger: typeof import('./components/ui/file-trigger').FileTrigger
  const Fragment: typeof import('react').Fragment
  const IconButton: typeof import('./components/ui/icon-button').IconButton
  const ImageExportThemeSelector: typeof import('./components/ui/image-export-theme-selector').ImageExportThemeSelector
  const Input: typeof import('./components/ui/input').Input
  const Kbd: typeof import('./components/ui/kbd').Kbd
  const LEGACY_BLOCK_TYPES: typeof import('./lib/blocknote-content/index').LEGACY_BLOCK_TYPES
  const Label: typeof import('./components/ui/label').Label
  const LucideIcons: typeof import('lucide-react')
  const MAX_FILE_ATTACHMENT_SIZE: typeof import('./lib/fileStorage').MAX_FILE_ATTACHMENT_SIZE
  const ONBOARDING_CHILD_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_CHILD_PAGE_CONTENT
  const ONBOARDING_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_PAGE_CONTENT
  const ONBOARDING_SECOND_CHILD_CONTENT: typeof import('./lib/onboarding').ONBOARDING_SECOND_CHILD_CONTENT
  const Popover: typeof import('./components/ui/popover').Popover
  const PopoverContent: typeof import('./components/ui/popover').PopoverContent
  const PopoverTrigger: typeof import('./components/ui/popover').PopoverTrigger
  const Portal: typeof import('./components/ui/portal').Portal
  const ScrollArea: typeof import('./components/ui/scroll-area').ScrollArea
  const ScrollBar: typeof import('./components/ui/scroll-area').ScrollBar
  const SelectableCard: typeof import('./components/ui/selectable-card').SelectableCard
  const Separator: typeof import('./components/ui/separator').Separator
  const Sheet: typeof import('./components/ui/sheet').Sheet
  const SheetClose: typeof import('./components/ui/sheet').SheetClose
  const SheetContent: typeof import('./components/ui/sheet').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet').SheetHeader
  const SheetOverlay: typeof import('./components/ui/sheet').SheetOverlay
  const SheetPortal: typeof import('./components/ui/sheet').SheetPortal
  const SheetTitle: typeof import('./components/ui/sheet').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet').SheetTrigger
  const Slider: typeof import('./components/ui/slider').Slider
  const Suspense: typeof import('react').Suspense
  const Switch: typeof import('./components/ui/switch').Switch
  const TIPS: typeof import('./lib/tips').TIPS
  const TITLE_HEADING_LEVEL: typeof import('./lib/blocknote-content/index').TITLE_HEADING_LEVEL
  const Tabs: typeof import('./components/ui/tabs').Tabs
  const TabsContent: typeof import('./components/ui/tabs').TabsContent
  const TabsList: typeof import('./components/ui/tabs').TabsList
  const TabsTrigger: typeof import('./components/ui/tabs').TabsTrigger
  const Textarea: typeof import('./components/ui/textarea').Textarea
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const Toggle: typeof import('./components/ui/toggle').Toggle
  const Tooltip: typeof import('./components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip').TooltipTrigger
  const UTOOLS_WINDOW_HEIGHT_DEFAULT: typeof import('./stores/useSettings').UTOOLS_WINDOW_HEIGHT_DEFAULT
  const UTOOLS_WINDOW_HEIGHT_MAX: typeof import('./stores/useSettings').UTOOLS_WINDOW_HEIGHT_MAX
  const UTOOLS_WINDOW_HEIGHT_MIN: typeof import('./stores/useSettings').UTOOLS_WINDOW_HEIGHT_MIN
  const UToolsAdapter: typeof import('./lib/utools').UToolsAdapter
  const UnderlineType: typeof import('./lib/docxExport/docxStyles').UnderlineType
  const VALID_BLOCK_TYPES: typeof import('./lib/blocknote-content/index').VALID_BLOCK_TYPES
  const applyFontVariables: typeof import('./lib/fontLoader').applyFontVariables
  const applyRolldownPolyfills: typeof import('./lib/rolldown-polyfill').applyRolldownPolyfills
  const blobToBase64: typeof import('./lib/imageProcessor').blobToBase64
  const blockToTable: typeof import('./lib/docxExport/docxBlocks').blockToTable
  const buildAiContextBundle: typeof import('./lib/ai-write/index').buildAiContextBundle
  const buildAiWorkspaceUserPrompt: typeof import('./lib/ai-write/index').buildAiWorkspaceUserPrompt
  const buildAiWritePlan: typeof import('./lib/ai-write/index').buildAiWritePlan
  const buildIntentRouterContext: typeof import('./lib/ai-intent-router').buildIntentRouterContext
  const buildLocalPageId: typeof import('./lib/local-folder-scanner').buildLocalPageId
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const classifyIntent: typeof import('./lib/ai-intent-router').classifyIntent
  const clearBlockSourceMap: typeof import('./lib/local-block-diff').clearBlockSourceMap
  const clearLocalPageMetadataCache: typeof import('./stores/usePages').clearLocalPageMetadataCache
  const clonePageContent: typeof import('./lib/blocknote-content/index').clonePageContent
  const clsx: typeof import('clsx').clsx
  const cn: typeof import('./lib/utils').cn
  const commitAiWritePlan: typeof import('./lib/ai-write/index').commitAiWritePlan
  const compressImage: typeof import('./lib/imageProcessor').compressImage
  const consumeFrontmatterForPath: typeof import('./lib/local-frontmatter-store').consumeFrontmatterForPath
  const containsMarkdownTable: typeof import('./lib/markdownTableParser').containsMarkdownTable
  const countWords: typeof import('./lib/content-text-extractor').countWords
  const createAiChatOnlyTarget: typeof import('./lib/ai-write/index').createAiChatOnlyTarget
  const createContext: typeof import('react').createContext
  const createEmptyBlockNoteContent: typeof import('./lib/blocknote-content/index').createEmptyBlockNoteContent
  const createRef: typeof import('react').createRef
  const createStickyTargetFromResolvedTarget: typeof import('./lib/ai-write/index').createStickyTargetFromResolvedTarget
  const decodeUnsupportedMarkdownForDisk: typeof import('./lib/markdown-raw-guard').decodeUnsupportedMarkdownForDisk
  const detectBlockScopeHeuristic: typeof import('./lib/ai-block-scope').detectBlockScopeHeuristic
  const emptyBlock: typeof import('./lib/blocknote-content/index').emptyBlock
  const encodeUnsupportedMarkdownForEditor: typeof import('./lib/markdown-raw-guard').encodeUnsupportedMarkdownForEditor
  const ensureFirstTitleHeading: typeof import('./lib/blocknote-content/index').ensureFirstTitleHeading
  const ensureToggleableHeadings: typeof import('./lib/blocknote-content').ensureToggleableHeadings
  const exportNotebooks: typeof import('./lib/export').exportNotebooks
  const exportPageToImage: typeof import('./lib/imageExport/index').exportPageToImage
  const exportSelectionToImage: typeof import('./lib/imageExport/index').exportSelectionToImage
  const exportToHTML: typeof import('./lib/export').exportToHTML
  const exportToImage: typeof import('./lib/imageExport/index').exportToImage
  const exportToJSON: typeof import('./lib/export').exportToJSON
  const exportToMarkdown: typeof import('./lib/export').exportToMarkdown
  const exportToWord: typeof import('./lib/docxExport/index').exportToWord
  const extractBlockNoteTitle: typeof import('./lib/blocknote-content/index').extractBlockNoteTitle
  const extractBlocksInRange: typeof import('./lib/ai-block-scope').extractBlocksInRange
  const extractCellText: typeof import('./lib/docxExport/docxBlocks').extractCellText
  const extractFrontmatter: typeof import('./lib/markdown-raw-guard').extractFrontmatter
  const extractInlineItems: typeof import('./lib/docxExport/docxStyles').extractInlineItems
  const extractPlainText: typeof import('./lib/blocknote-content/index').extractPlainText
  const extractStructureSummary: typeof import('./lib/content-text-extractor').extractStructureSummary
  const extractTextFromContent: typeof import('./lib/content-text-extractor').extractTextFromContent
  const extractTitleFromContent: typeof import('./lib/content-text-extractor').extractTitleFromContent
  const fetchCustomAIModels: typeof import('./lib/ai-provider').fetchCustomAIModels
  const fileStorage: typeof import('./lib/fileStorage').fileStorage
  const flushEditorContent: typeof import('./stores/usePages').flushEditorContent
  const flushUToolsStorageWrites: typeof import('./lib/storage').flushUToolsStorageWrites
  const formatAttachmentSize: typeof import('./lib/fileStorage').formatAttachmentSize
  const formatShortcut: typeof import('./lib/utils').formatShortcut
  const forwardRef: typeof import('react').forwardRef
  const generateDocxBuffer: typeof import('./lib/docxExport/index').generateDocxBuffer
  const getAIAnalyticsContext: typeof import('./lib/analytics').getAIAnalyticsContext
  const getAIAvailability: typeof import('./lib/ai-provider').getAIAvailability
  const getAIErrorType: typeof import('./lib/analytics').getAIErrorType
  const getAIProviderMode: typeof import('./lib/ai-provider').getAIProviderMode
  const getAnalyticsContext: typeof import('./lib/analytics').getAnalyticsContext
  const getAnalyticsInstallId: typeof import('./lib/analytics').getAnalyticsInstallId
  const getAnalyticsSessionId: typeof import('./lib/analytics').getAnalyticsSessionId
  const getAttachmentBadgeLabel: typeof import('./lib/fileStorage').getAttachmentBadgeLabel
  const getAvailableAIModelOptions: typeof import('./lib/ai-provider').getAvailableAIModelOptions
  const getAvailableUToolsAiModels: typeof import('./lib/utools-ai').getAvailableUToolsAiModels
  const getCardTheme: typeof import('./lib/imageExport/index').getCardTheme
  const getContentSignature: typeof import('./lib/blocknote-content/index').getContentSignature
  const getCustomAIApiKey: typeof import('./lib/ai-provider').getCustomAIApiKey
  const getCustomAIBaseURL: typeof import('./lib/ai-provider').getCustomAIBaseURL
  const getDbStorageItem: typeof import('./lib/storage').getDbStorageItem
  const getDefaultCustomAIBaseURL: typeof import('./lib/ai-provider').getDefaultCustomAIBaseURL
  const getEditorFontFamilies: typeof import('./lib/fontLoader').getEditorFontFamilies
  const getFileUploadAvailability: typeof import('./lib/fileStorage').getFileUploadAvailability
  const getGlobalScrollActivitySnapshot: typeof import('./hooks/useGlobalScrollActivity').getGlobalScrollActivitySnapshot
  const getImageFromClipboard: typeof import('./lib/imageProcessor').getImageFromClipboard
  const getImageStorage: typeof import('./lib/docxExport/docxImages').getImageStorage
  const getNotebookAnalyticsContext: typeof import('./lib/analytics').getNotebookAnalyticsContext
  const getPageTitle: typeof import('./lib/page-title').getPageTitle
  const getPlatformKind: typeof import('./lib/utils').getPlatformKind
  const getPrimaryModifierKeyDisplay: typeof import('./lib/utils').getPrimaryModifierKeyDisplay
  const getPrimaryModifierKeyLabel: typeof import('./lib/utils').getPrimaryModifierKeyLabel
  const getRandomBlockAccentColor: typeof import('./lib/blockColorPresets').getRandomBlockAccentColor
  const getRandomBlockColorPair: typeof import('./lib/blockColorPresets').getRandomBlockColorPair
  const getRandomTip: typeof import('./lib/tips').getRandomTip
  const getStoredAIModelOptions: typeof import('./lib/ai-provider').getStoredAIModelOptions
  const hasStructuredBlocks: typeof import('./lib/blocknote-content/index').hasStructuredBlocks
  const hashBlock: typeof import('./lib/local-block-diff').hashBlock
  const importFile: typeof import('./lib/export').importFile
  const importFromJSON: typeof import('./lib/export').importFromJSON
  const importFromMarkdown: typeof import('./lib/export').importFromMarkdown
  const importMarkdownFragment: typeof import('./lib/export').importMarkdownFragment
  const importNotebooksFromZip: typeof import('./lib/export').importNotebooksFromZip
  const initAnalytics: typeof import('./lib/analytics').initAnalytics
  const inlineToTextRuns: typeof import('./lib/docxExport/docxStyles').inlineToTextRuns
  const isAnalyticsInitialized: typeof import('./lib/analytics').isAnalyticsInitialized
  const isBlockNoteContent: typeof import('./lib/blocknote-content/index').isBlockNoteContent
  const isMacPlatform: typeof import('./lib/utils').isMacPlatform
  const isUToolsAiSupported: typeof import('./lib/utools-ai').isUToolsAiSupported
  const isValidImageUrl: typeof import('./lib/imageProcessor').isValidImageUrl
  const jsonContentToMarkdown: typeof import('./lib/export').jsonContentToMarkdown
  const lazy: typeof import('react').lazy
  const mapUToolsAiModelsToOptions: typeof import('./lib/ai-provider').mapUToolsAiModelsToOptions
  const memo: typeof import('react').memo
  const migrateCodeStyleTo2026: typeof import('./lib/code-style-migration').migrateCodeStyleTo2026
  const mimeToImageType: typeof import('./lib/docxExport/docxImages').mimeToImageType
  const normalizeBlockContent: typeof import('./lib/blocknote-content/index').normalizeBlockContent
  const normalizeBlocks: typeof import('./lib/blocknote-content/index').normalizeBlocks
  const normalizeExternalUrl: typeof import('./lib/openExternalUrl').normalizeExternalUrl
  const normalizePageContent: typeof import('./lib/blocknote-content/index').normalizePageContent
  const onboardingChildPageContent: typeof import('./lib/onboardingContent').onboardingChildPageContent
  const onboardingPageContent: typeof import('./lib/onboardingContent').onboardingPageContent
  const onboardingSecondChildContent: typeof import('./lib/onboardingContent').onboardingSecondChildContent
  const openExternalUrl: typeof import('./lib/openExternalUrl').openExternalUrl
  const organizeToggleHeadingSections: typeof import('./lib/blocknote-content').organizeToggleHeadingSections
  const parseBase64Image: typeof import('./lib/docxExport/docxImages').parseBase64Image
  const parseIntentResponse: typeof import('./lib/ai-intent-router').parseIntentResponse
  const parseMarkdownTableToHtml: typeof import('./lib/markdownTableParser').parseMarkdownTableToHtml
  const parseMarkdownToHtml: typeof import('./lib/markdownTableParser').parseMarkdownToHtml
  const peekFrontmatterForPath: typeof import('./lib/local-frontmatter-store').peekFrontmatterForPath
  const preloadFonts: typeof import('./lib/fontLoader').preloadFonts
  const processBlockChildren: typeof import('./lib/docxExport/docxBlocks').processBlockChildren
  const processImageForStorage: typeof import('./lib/imageProcessor').processImageForStorage
  const processImageForStorageV2: typeof import('./lib/imageProcessor').processImageForStorageV2
  const readDbStorageJSON: typeof import('./lib/storage').readDbStorageJSON
  const readPersistentDismissState: typeof import('./lib/dismiss-state').readPersistentDismissState
  const removeDbStorageItem: typeof import('./lib/storage').removeDbStorageItem
  const resetAnalytics: typeof import('./lib/analytics').resetAnalytics
  const resolveAiTargetFromSelection: typeof import('./lib/ai-write/index').resolveAiTargetFromSelection
  const resolveAiTargetIntent: typeof import('./lib/ai-write/index').resolveAiTargetIntent
  const resolveAiTargetReference: typeof import('./lib/ai-write/index').resolveAiTargetReference
  const resolveAiTargetSelection: typeof import('./lib/ai-write/index').resolveAiTargetSelection
  const resolveBlockScope: typeof import('./lib/ai-block-scope').resolveBlockScope
  const resolveImageToBuffer: typeof import('./lib/docxExport/docxImages').resolveImageToBuffer
  const resolvedTargetToSelection: typeof import('./lib/ai-write/index').resolvedTargetToSelection
  const runAIText: typeof import('./lib/ai-provider').runAIText
  const runAITextStream: typeof import('./lib/ai-provider').runAITextStream
  const runCodeStyleMigration2026: typeof import('./lib/code-style-migration').runCodeStyleMigration2026
  const sanitizeFileName: typeof import('./lib/fileStorage').sanitizeFileName
  const saveBlobAndReveal: typeof import('./lib/export').saveBlobAndReveal
  const scanLocalFolderPages: typeof import('./lib/local-folder-scanner').scanLocalFolderPages
  const serializeWithBlockDiff: typeof import('./lib/local-block-diff').serializeWithBlockDiff
  const setBlockSourceMap: typeof import('./lib/local-block-diff').setBlockSourceMap
  const setDbStorageItem: typeof import('./lib/storage').setDbStorageItem
  const setFrontmatterForPath: typeof import('./lib/local-frontmatter-store').setFrontmatterForPath
  const simpleExtractText: typeof import('./lib/blocknote-content/index').simpleExtractText
  const splitMarkdownIntoBlocks: typeof import('./lib/local-block-diff').splitMarkdownIntoBlocks
  const startTransition: typeof import('react').startTransition
  const stickyTargetToSelection: typeof import('./lib/ai-write/index').stickyTargetToSelection
  const subscribeGlobalScrollActivity: typeof import('./hooks/useGlobalScrollActivity').subscribeGlobalScrollActivity
  const syncAIAnalyticsContext: typeof import('./lib/analytics').syncAIAnalyticsContext
  const syncAnalyticsContext: typeof import('./lib/analytics').syncAnalyticsContext
  const syncNotebookAnalyticsContext: typeof import('./lib/analytics').syncNotebookAnalyticsContext
  const titleHeadingBlock: typeof import('./lib/blocknote-content/index').titleHeadingBlock
  const toggleVariants: typeof import('./components/ui/toggle').toggleVariants
  const trackEvent: typeof import('./lib/analytics').trackEvent
  const uToolsStorage: typeof import('./lib/storage').uToolsStorage
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAiSessions: typeof import('./stores/useAiSessions').useAiSessions
  const useAiStatus: typeof import('./stores/useAiStatus').useAiStatus
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useContextMenu: typeof import('./stores/useContextMenu').useContextMenu
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeletePageWithUndo: typeof import('./hooks/useDeletePageWithUndo').useDeletePageWithUndo
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormatCode: typeof import('./hooks/useFormatCode').useFormatCode
  const useFormattingToolbarAi: typeof import('./stores/useFormattingToolbarAi').useFormattingToolbarAi
  const useGlobalScrollActivity: typeof import('./hooks/useGlobalScrollActivity').useGlobalScrollActivity
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useNotebooks: typeof import('./stores/useNotebooks').useNotebooks
  const useOptimistic: typeof import('react').useOptimistic
  const usePages: typeof import('./stores/usePages').usePages
  const usePersistentDismissState: typeof import('./hooks/usePersistentDismissState').usePersistentDismissState
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useSettings: typeof import('./stores/useSettings').useSettings
  const useState: typeof import('react').useState
  const useStickyNote: typeof import('./stores/useStickyNote').useStickyNote
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTabs: typeof import('./stores/useTabs').useTabs
  const useTransition: typeof import('react').useTransition
  const verdictToTargetMode: typeof import('./lib/ai-intent-router').verdictToTargetMode
  const waitForFonts: typeof import('./lib/fontLoader').waitForFonts
  const writeDbStorageJSON: typeof import('./lib/storage').writeDbStorageJSON
  const writePersistentDismissState: typeof import('./lib/dismiss-state').writePersistentDismissState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AiSessionMessage, AiSession } from './stores/useAiSessions'
  import('./stores/useAiSessions')
  // @ts-ignore
  export type { AiActivityPhase } from './stores/useAiStatus'
  import('./stores/useAiStatus')
  // @ts-ignore
  export type { Notebook, LocalFolderLoadStatus, LocalFolderLoadState } from './stores/useNotebooks'
  import('./stores/useNotebooks')
  // @ts-ignore
  export type { SearchProvider, Theme, CodeStyle, UToolsSettings, AISettings, DesktopHotkeyStatusState, DesktopHotkeyStatus, DesktopSettings, PrivacySettings, FontConfig, CustomFonts, CustomAction, UIFontSize } from './stores/useSettings'
  import('./stores/useSettings')
  // @ts-ignore
  export type { TabItem } from './stores/useTabs'
  import('./stores/useTabs')
  // @ts-ignore
  export type { AiBlockScopeKind, AiBlockScopeRange, AiBlockScope } from './lib/ai-block-scope'
  import('./lib/ai-block-scope')
  // @ts-ignore
  export type { IntentVerdict, IntentRouterContext, IntentRouterResult } from './lib/ai-intent-router'
  import('./lib/ai-intent-router')
  // @ts-ignore
  export type { CustomAIProtocol, AIModelOption, AIProviderMode, AIReasoningLevel, AISettingsLike, AIMessage, AIStreamPhase, AIStreamUpdate, AIRequestOverrides, RunAITextOptions, RunAITextStreamOptions } from './lib/ai-provider'
  import('./lib/ai-provider')
  // @ts-ignore
  export type { AiWriteAction, AiBlockRange, AiTargetMode, AiTargetSource, AiTargetSelection, AiTargetRef, AiStickyTarget, AiResolvedTarget, AiWritePlan, AiContextBundle } from './lib/ai-write/index'
  import('./lib/ai-write/index')
  // @ts-ignore
  export type { ProviderSource, CustomProtocolValue, AnalyticsContext, AnalyticsInitOptions } from './lib/analytics'
  import('./lib/analytics')
  // @ts-ignore
  export type { BlockNoteContent, LegacyPageContent, PageContent } from './lib/blocknote-content/index'
  import('./lib/blocknote-content/index')
  // @ts-ignore
  export type { InlineItem } from './lib/docxExport/docxStyles'
  import('./lib/docxExport/docxStyles')
  // @ts-ignore
  export type { ImageBufferResult } from './lib/docxExport/docxImages'
  import('./lib/docxExport/docxImages')
  // @ts-ignore
  export type { ExportOptions, ImportResult } from './lib/export'
  import('./lib/export')
  // @ts-ignore
  export type { CardTheme, CardThemeId, WatermarkConfig } from './lib/imageExport/index'
  import('./lib/imageExport/index')
  // @ts-ignore
  export type { PlatformKind } from './lib/utils'
  import('./lib/utils')
  // @ts-ignore
  export type { UToolsAiModel } from './lib/utools-ai'
  import('./lib/utools-ai')
  // @ts-ignore
  export type { UToolsAdapter, SublistItem, UserInfo } from './lib/utools'
  import('./lib/utools')
  // @ts-ignore
  export type { ButtonProps } from './components/ui/button'
  import('./components/ui/button')
  // @ts-ignore
  export type { IconButtonProps } from './components/ui/icon-button'
  import('./components/ui/icon-button')
  // @ts-ignore
  export type { SelectableCardProps } from './components/ui/selectable-card'
  import('./components/ui/selectable-card')
}
