/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Check: typeof import('lucide-react').Check
  const ChevronDown: typeof import('lucide-react').ChevronDown
  const ChevronRight: typeof import('lucide-react').ChevronRight
  const Code: typeof import('lucide-react').Code
  const DEFAULT_SEARCH_PROVIDERS: typeof import('./stores/useSettings').DEFAULT_SEARCH_PROVIDERS
  const FileText: typeof import('lucide-react').FileText
  const Fragment: typeof import('react').Fragment
  const Image: typeof import('lucide-react').Image
  const Link: typeof import('lucide-react').Link
  const List: typeof import('lucide-react').List
  const ListOrdered: typeof import('lucide-react').ListOrdered
  const Menu: typeof import('lucide-react').Menu
  const MoreHorizontal: typeof import('lucide-react').MoreHorizontal
  const Plus: typeof import('lucide-react').Plus
  const Search: typeof import('lucide-react').Search
  const Settings: typeof import('lucide-react').Settings
  const Suspense: typeof import('react').Suspense
  const Trash2: typeof import('lucide-react').Trash2
  const UToolsAdapter: typeof import('./lib/utools').UToolsAdapter
  const X: typeof import('lucide-react').X
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const clsx: typeof import('clsx').clsx
  const cn: typeof import('./lib/utils').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const exportToHTML: typeof import('./lib/export').exportToHTML
  const exportToJSON: typeof import('./lib/export').exportToJSON
  const exportToMarkdown: typeof import('./lib/export').exportToMarkdown
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const uToolsStorage: typeof import('./lib/storage').uToolsStorage
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const usePages: typeof import('./stores/usePages').usePages
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useSettings: typeof import('./stores/useSettings').useSettings
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SearchProvider, Theme } from './stores/useSettings'
  import('./stores/useSettings')
  // @ts-ignore
  export type { UToolsAdapter, UserInfo } from './lib/utools'
  import('./lib/utools')
}
