// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const EDITOR_CONTEXT_UI_GAP: typeof import('../components/editor/utils/editorContextUi').EDITOR_CONTEXT_UI_GAP
  const FormattingToolbarHoldContext: typeof import('../components/editor/state/formattingToolbarHold').FormattingToolbarHoldContext
  const LEGACY_BLOCK_TYPES: typeof import('../components/editor/utils/blocknote-content/index').LEGACY_BLOCK_TYPES
  const LIST_PASTE_BLOCK_TYPES: typeof import('../components/editor/utils/multilinePaste').LIST_PASTE_BLOCK_TYPES
  const TITLE_HEADING_LEVEL: typeof import('../components/editor/utils/blocknote-content/index').TITLE_HEADING_LEVEL
  const UNTITLED_PAGE_TITLE: typeof import('../components/editor/utils/page-title').UNTITLED_PAGE_TITLE
  const VALID_BLOCK_TYPES: typeof import('../components/editor/utils/blocknote-content/index').VALID_BLOCK_TYPES
  const buildInheritedPasteBlocks: typeof import('../components/editor/utils/multilinePaste').buildInheritedPasteBlocks
  const buildSoftWrapInlineFromMarkdown: typeof import('../components/editor/utils/softWrapPaste').buildSoftWrapInlineFromMarkdown
  const buildSoftWrapPasteInline: typeof import('../components/editor/utils/softWrapPaste').buildSoftWrapPasteInline
  const cachePasteTarget: typeof import('../components/editor/hooks/useEditorPaste').cachePasteTarget
  const clearEditorSelectedBlocksCache: typeof import('../components/editor/utils/selection').clearEditorSelectedBlocksCache
  const clipboardHasPasteableImage: typeof import('../components/editor/utils/pasteClipboardImage').clipboardHasPasteableImage
  const clipboardHasPasteableMedia: typeof import('../components/editor/utils/pasteClipboardImage').clipboardHasPasteableMedia
  const clonePageContent: typeof import('../components/editor/utils/blocknote-content/index').clonePageContent
  const countWords: typeof import('../components/editor/utils/content-text-extractor').countWords
  const createDebounce: typeof import('../components/editor/utils/debounce').createDebounce
  const createEditorSafeContent: typeof import('../components/editor/utils/blocknote-content/index').createEditorSafeContent
  const createEmptyBlockNoteContent: typeof import('../components/editor/utils/blocknote-content/index').createEmptyBlockNoteContent
  const createEmptyLocalPageContent: typeof import('../components/editor/utils/blocknote-content/index').createEmptyLocalPageContent
  const emptyBlock: typeof import('../components/editor/utils/blocknote-content/index').emptyBlock
  const ensureBodyParagraphAfterTitle: typeof import('../components/editor/utils/blocknote-content/index').ensureBodyParagraphAfterTitle
  const ensureFirstTitleHeading: typeof import('../components/editor/utils/blocknote-content/index').ensureFirstTitleHeading
  const extractBlockNoteTitle: typeof import('../components/editor/utils/blocknote-content/index').extractBlockNoteTitle
  const extractClipboardImageFiles: typeof import('../components/editor/utils/pasteClipboardImage').extractClipboardImageFiles
  const extractPlainText: typeof import('../components/editor/utils/blocknote-content/index').extractPlainText
  const extractStructureSummary: typeof import('../components/editor/utils/content-text-extractor').extractStructureSummary
  const extractTextFromContent: typeof import('../components/editor/utils/content-text-extractor').extractTextFromContent
  const extractTitleFromContent: typeof import('../components/editor/utils/content-text-extractor').extractTitleFromContent
  const findActivePageMentionQuery: typeof import('../components/editor/utils/slashMenuPolicy').findActivePageMentionQuery
  const findNonOverlappingToolbarPosition: typeof import('../components/editor/utils/formattingToolbarPosition').findNonOverlappingToolbarPosition
  const finishPasteAtAnchor: typeof import('../components/editor/hooks/useEditorPaste').finishPasteAtAnchor
  const flattenParsedBlocksToSoftWrapInline: typeof import('../components/editor/utils/softWrapPaste').flattenParsedBlocksToSoftWrapInline
  const focusPastedBlock: typeof import('../components/editor/utils/pasteAtCursor').focusPastedBlock
  const getActiveGooseNoteEditor: typeof import('../components/editor/utils/selection').getActiveGooseNoteEditor
  const getCompactSlashMenuFloatingOptions: typeof import('../components/editor/utils/compactSlashMenuFloating').getCompactSlashMenuFloatingOptions
  const getContentSignature: typeof import('../components/editor/utils/blocknote-content/index').getContentSignature
  const getEditorSelectedBlocksForExport: typeof import('../components/editor/utils/selection').getEditorSelectedBlocksForExport
  const getEditorSelectionPlainText: typeof import('../components/editor/utils/clipboardPlainText').getEditorSelectionPlainText
  const getEditorUiScale: typeof import('../components/editor/utils/editorContextUi').getEditorUiScale
  const getElementFromNode: typeof import('../components/editor/utils/selection').getElementFromNode
  const getFormattingToolbarReferenceRect: typeof import('../components/editor/utils/formattingToolbarReference').getFormattingToolbarReferenceRect
  const getMultiBlockToolbarEdgeRect: typeof import('../components/editor/utils/formattingToolbarReference').getMultiBlockToolbarEdgeRect
  const getPageTitle: typeof import('../components/editor/utils/page-title').getPageTitle
  const getScaledEditorUiPx: typeof import('../components/editor/utils/editorContextUi').getScaledEditorUiPx
  const getSelectedCellPlainText: typeof import('../components/editor/utils/selection').getSelectedCellPlainText
  const getSelectedImageUrl: typeof import('../components/editor/utils/selection').getSelectedImageUrl
  const getSelectedPlainTextContext: typeof import('../components/editor/utils/selection').getSelectedPlainTextContext
  const hasStructuredBlocks: typeof import('../components/editor/utils/blocknote-content/index').hasStructuredBlocks
  const hasStyledSoftWrapItems: typeof import('../components/editor/utils/softWrapPaste').hasStyledSoftWrapItems
  const htmlHasInlineFormatting: typeof import('../components/editor/utils/softWrapPaste').htmlHasInlineFormatting
  const htmlHasNonDefaultGooseBlockAttrs: typeof import('../components/editor/utils/clipboardPolicy').htmlHasNonDefaultGooseBlockAttrs
  const htmlHasNonTextPasteBlocks: typeof import('../components/editor/utils/multilinePaste').htmlHasNonTextPasteBlocks
  const htmlHasPreservableFormatting: typeof import('../components/editor/utils/clipboardPolicy').htmlHasPreservableFormatting
  const htmlHasRichPasteContent: typeof import('../components/editor/utils/multilinePaste').htmlHasRichPasteContent
  const htmlLooksLikeBlockNoteClipboard: typeof import('../components/editor/utils/multilinePaste').htmlLooksLikeBlockNoteClipboard
  const htmlToPlainTextForPaste: typeof import('../components/editor/utils/multilinePaste').htmlToPlainTextForPaste
  const insertSoftWrappedInline: typeof import('../components/editor/utils/softWrapPaste').insertSoftWrappedInline
  const insertSoftWrappedLines: typeof import('../components/editor/utils/softWrapPaste').insertSoftWrappedLines
  const inspectPasteContainer: typeof import('../components/editor/utils/multilinePaste').inspectPasteContainer
  const isBlockNoteContent: typeof import('../components/editor/utils/blocknote-content/index').isBlockNoteContent
  const isBottomEditorBlankClick: typeof import('../components/editor/utils/selection').isBottomEditorBlankClick
  const isEmptyInlineBlock: typeof import('../components/editor/utils/pasteAtCursor').isEmptyInlineBlock
  const isImageUploadFile: typeof import('../components/editor/utils/pasteClipboardImage').isImageUploadFile
  const isInteractiveEditorTarget: typeof import('../components/editor/utils/selection').isInteractiveEditorTarget
  const isLinkworthyText: typeof import('../components/editor/utils/clipboardPolicy').isLinkworthyText
  const isListPasteBlockType: typeof import('../components/editor/utils/multilinePaste').isListPasteBlockType
  const isPageMentionBoundaryChar: typeof import('../components/editor/utils/slashMenuPolicy').isPageMentionBoundaryChar
  const isPasteableClipboardImageFile: typeof import('../components/editor/utils/pasteClipboardImage').isPasteableClipboardImageFile
  const isPasteableClipboardVideoFile: typeof import('../components/editor/utils/pasteClipboardImage').isPasteableClipboardVideoFile
  const isSuggestionMenuAcceptKey: typeof import('../components/editor/utils/slashMenuPolicy').isSuggestionMenuAcceptKey
  const isValidUrl: typeof import('../components/editor/utils/clipboardPolicy').isValidUrl
  const isWholeTableCellSelection: typeof import('../components/editor/utils/selection').isWholeTableCellSelection
  const looksLikeBlockStructure: typeof import('../components/editor/utils/clipboardPolicy').looksLikeBlockStructure
  const looksLikeMarkdownFragment: typeof import('../components/editor/utils/clipboardMarkdown').looksLikeMarkdownFragment
  const looksLikeMermaidDiagram: typeof import('../components/editor/utils/clipboardMarkdown').looksLikeMermaidDiagram
  const mentionTriggerDeleteRange: typeof import('../components/editor/utils/slashMenuPolicy').mentionTriggerDeleteRange
  const needsBodyParagraphAfterTitle: typeof import('../components/editor/utils/blocknote-content/index').needsBodyParagraphAfterTitle
  const normalizeBlockContent: typeof import('../components/editor/utils/blocknote-content/index').normalizeBlockContent
  const normalizeBlocks: typeof import('../components/editor/utils/blocknote-content/index').normalizeBlocks
  const normalizeClipboardLineEndings: typeof import('../components/editor/utils/clipboardMarkdown').normalizeClipboardLineEndings
  const normalizeClipboardListMarkers: typeof import('../components/editor/utils/clipboardMarkdown').normalizeClipboardListMarkers
  const normalizeEditorUiScale: typeof import('../components/editor/utils/editorContextUi').normalizeEditorUiScale
  const normalizeHeadingSectionFold: typeof import('../components/editor/utils/blocknote-content/index').normalizeHeadingSectionFold
  const normalizeHeadingToggleableFlags: typeof import('../components/editor/utils/blocknote-content/index').normalizeHeadingToggleableFlags
  const normalizeMarkdownPasteText: typeof import('../components/editor/utils/clipboardMarkdown').normalizeMarkdownPasteText
  const normalizePageContent: typeof import('../components/editor/utils/blocknote-content/index').normalizePageContent
  const normalizePageTitle: typeof import('../components/editor/utils/page-title').normalizePageTitle
  const openResourceExternally: typeof import('../components/editor/utils/openResourceExternally').openResourceExternally
  const parseMarkdownLink: typeof import('../components/editor/utils/clipboardMarkdown').parseMarkdownLink
  const pasteBlocksAtCursor: typeof import('../components/editor/utils/pasteAtCursor').pasteBlocksAtCursor
  const pasteClipboardFilesFromClipboard: typeof import('../components/editor/utils/pasteClipboardFilesFromClipboard').pasteClipboardFilesFromClipboard
  const pasteClipboardHtmlAsBlocks: typeof import('../components/editor/hooks/useEditorPaste').pasteClipboardHtmlAsBlocks
  const pasteLinesAsBlocks: typeof import('../components/editor/hooks/useEditorPaste').pasteLinesAsBlocks
  const plainHasGooseMarkdownMarkers: typeof import('../components/editor/hooks/useEditorPaste').plainHasGooseMarkdownMarkers
  const planMultilinePaste: typeof import('../components/editor/utils/multilinePaste').planMultilinePaste
  const readLiveEditorSelectedBlocks: typeof import('../components/editor/utils/selection').readLiveEditorSelectedBlocks
  const reconcilePageMentionSuggestionMenu: typeof import('../components/editor/utils/slashMenuPolicy').reconcilePageMentionSuggestionMenu
  const reconcileSlashSuggestionMenu: typeof import('../components/editor/utils/slashMenuPolicy').reconcileSlashSuggestionMenu
  const rememberEditorSelectedBlocks: typeof import('../components/editor/utils/selection').rememberEditorSelectedBlocks
  const rememberFormattingToolbarRect: typeof import('../components/editor/utils/formattingToolbarReference').rememberFormattingToolbarRect
  const resolveImageMimeForUpload: typeof import('../components/editor/utils/pasteClipboardImage').resolveImageMimeForUpload
  const resolveInheritedPasteBlockType: typeof import('../components/editor/utils/multilinePaste').resolveInheritedPasteBlockType
  const resolvePasteAnchor: typeof import('../components/editor/hooks/useEditorPaste').resolvePasteAnchor
  const resolvePasteLines: typeof import('../components/editor/utils/multilinePaste').resolvePasteLines
  const resolvePhysicalResourcePath: typeof import('../components/editor/utils/openResourceExternally').resolvePhysicalResourcePath
  const serializeDocRangePlainText: typeof import('../components/editor/utils/clipboardPlainText').serializeDocRangePlainText
  const serializeSlicePlainText: typeof import('../components/editor/utils/clipboardPlainText').serializeSlicePlainText
  const shouldIsolateTitleStructurePaste: typeof import('../components/editor/hooks/useEditorPaste').shouldIsolateTitleStructurePaste
  const shouldOpenPageMentionSuggestionMenu: typeof import('../components/editor/utils/slashMenuPolicy').shouldOpenPageMentionSuggestionMenu
  const shouldOpenSlashSuggestionMenu: typeof import('../components/editor/utils/slashMenuPolicy').shouldOpenSlashSuggestionMenu
  const shouldPasteClipboardAsBlocks: typeof import('../components/editor/hooks/useEditorPaste').shouldPasteClipboardAsBlocks
  const shouldPasteHtmlAsBlocks: typeof import('../components/editor/hooks/useEditorPaste').shouldPasteHtmlAsBlocks
  const shouldPreferPlainMultilinePaste: typeof import('../components/editor/utils/multilinePaste').shouldPreferPlainMultilinePaste
  const shouldPreferVisibleSelectionText: typeof import('../components/editor/utils/clipboardMarkdown').shouldPreferVisibleSelectionText
  const shouldSplitMultilinePaste: typeof import('../components/editor/utils/multilinePaste').shouldSplitMultilinePaste
  const shouldUploadViaImageStorage: typeof import('../components/editor/utils/pasteClipboardImage').shouldUploadViaImageStorage
  const simpleExtractText: typeof import('../components/editor/utils/blocknote-content/index').simpleExtractText
  const splitPlainTextPasteLines: typeof import('../components/editor/utils/multilinePaste').splitPlainTextPasteLines
  const stripInheritedListPrefix: typeof import('../components/editor/utils/multilinePaste').stripInheritedListPrefix
  const stripMarkdownHardBreaks: typeof import('../components/editor/utils/clipboardMarkdown').stripMarkdownHardBreaks
  const titleHeadingBlock: typeof import('../components/editor/utils/blocknote-content/index').titleHeadingBlock
  const toInsertableInlineContent: typeof import('../components/editor/utils/softWrapPaste').toInsertableInlineContent
  const tryPasteGooseMarkdownFragment: typeof import('../components/editor/hooks/useEditorPaste').tryPasteGooseMarkdownFragment
  const uploadEditorFile: typeof import('../components/editor/utils/uploadEditorFile').uploadEditorFile
  const useCenteredActiveItemScroll: typeof import('../components/editor/hooks/useCenteredActiveItemScroll').useCenteredActiveItemScroll
  const useContextMenu: typeof import('../components/editor/state/contextMenu').useContextMenu
  const useEditorPaste: typeof import('../components/editor/hooks/useEditorPaste').useEditorPaste
  const useEditorShortcuts: typeof import('../components/editor/hooks/useEditorShortcuts').useEditorShortcuts
  const useEditorUiScale: typeof import('../components/editor/hooks/useEditorUiScale').useEditorUiScale
  const useFormatCode: typeof import('../components/editor/hooks/useFormatCode').useFormatCode
  const useFormattingToolbarAi: typeof import('../components/editor/state/formattingToolbarAi').useFormattingToolbarAi
  const useFormattingToolbarHold: typeof import('../components/editor/state/formattingToolbarHold').useFormattingToolbarHold
  const useGlobalScrollActivity: typeof import('../components/editor/hooks/useGlobalScrollActivity').useGlobalScrollActivity
  const withInternalPageTitle: typeof import('../components/editor/utils/page-title').withInternalPageTitle
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CachedPasteTarget } from '../components/editor/hooks/useEditorPaste'
  import('../components/editor/hooks/useEditorPaste')
  // @ts-ignore
  export type { BlockNoteContent, LegacyPageContent, PageContent } from '../components/editor/utils/blocknote-content/index'
  import('../components/editor/utils/blocknote-content/index')
  // @ts-ignore
  export type { SerializePlainTextOptions } from '../components/editor/utils/clipboardPlainText'
  import('../components/editor/utils/clipboardPlainText')
  // @ts-ignore
  export type { ToolbarPoint, ToolbarRect } from '../components/editor/utils/formattingToolbarPosition'
  import('../components/editor/utils/formattingToolbarPosition')
  // @ts-ignore
  export type { ToolbarEdgeSide, ToolbarReferenceRect } from '../components/editor/utils/formattingToolbarReference'
  import('../components/editor/utils/formattingToolbarReference')
  // @ts-ignore
  export type { InheritedPasteBlock, ListPasteBlockType, MultilinePastePlan, PasteContainerInspect } from '../components/editor/utils/multilinePaste'
  import('../components/editor/utils/multilinePaste')
  // @ts-ignore
  export type { OpenExternalResourceResult } from '../components/editor/utils/openResourceExternally'
  import('../components/editor/utils/openResourceExternally')
  // @ts-ignore
  export type { PasteAtCursorEditor } from '../components/editor/utils/pasteAtCursor'
  import('../components/editor/utils/pasteAtCursor')
  // @ts-ignore
  export type { ClipboardImageSource } from '../components/editor/utils/pasteClipboardImage'
  import('../components/editor/utils/pasteClipboardImage')
  // @ts-ignore
  export type { SlashMenuPagePolicy } from '../components/editor/utils/slashMenuPolicy'
  import('../components/editor/utils/slashMenuPolicy')
  // @ts-ignore
  export type { SoftWrapInlineItem } from '../components/editor/utils/softWrapPaste'
  import('../components/editor/utils/softWrapPaste')
  // @ts-ignore
  export type { EditorFileUploadDeps } from '../components/editor/utils/uploadEditorFile'
  import('../components/editor/utils/uploadEditorFile')
}
