// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const isDuplicateCompositionEndChange: typeof import('../hooks/useImeInput').isDuplicateCompositionEndChange
  const isImeKeyboardEvent: typeof import('../hooks/useImeInput').isImeKeyboardEvent
  const resolveTheme: typeof import('../hooks/useResolvedTheme').resolveTheme
  const shouldSkipAppHotkeyEvent: typeof import('../hooks/useImeInput').shouldSkipAppHotkeyEvent
  const useAppHotkeys: typeof import('../hooks/useAppHotkeys').useAppHotkeys
  const useDesktopHotkeys: typeof import('../hooks/useDesktopHotkeys').useDesktopHotkeys
  const useDesktopWindowTitleSync: typeof import('../hooks/useDesktopWindowTitle').useDesktopWindowTitleSync
  const useEffectiveSidebarCollapsed: typeof import('../hooks/useWorkspaceViewportCollapse').useEffectiveSidebarCollapsed
  const useHistoryRecorder: typeof import('../hooks/useHistoryRecorder').useHistoryRecorder
  const useImeInput: typeof import('../hooks/useImeInput').useImeInput
  const useNativeContextMenuGuard: typeof import('../hooks/useNativeContextMenuGuard').useNativeContextMenuGuard
  const usePersistentDismissState: typeof import('../hooks/usePersistentDismissState').usePersistentDismissState
  const usePluginEvents: typeof import('../hooks/usePluginEvents').usePluginEvents
  const useResolvedTheme: typeof import('../hooks/useResolvedTheme').useResolvedTheme
  const useWindowAlwaysOnTop: typeof import('../hooks/useWindowAlwaysOnTop').useWindowAlwaysOnTop
  const useWorkspaceViewportCollapse: typeof import('../hooks/useWorkspaceViewportCollapse').useWorkspaceViewportCollapse
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ResolvedTheme } from '../hooks/useResolvedTheme'
  import('../hooks/useResolvedTheme')
}
