// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const AI_PROVIDER_PRESETS: typeof import('../lib/ai-provider/index').AI_PROVIDER_PRESETS
  const CARD_THEMES: typeof import('../lib/imageExport/index').CARD_THEMES
  const DEEPSEEK_BASE_URL: typeof import('../lib/ai-provider/index').DEEPSEEK_BASE_URL
  const DEFAULT_CLAUDE_BASE_URL: typeof import('../lib/ai-provider/index').DEFAULT_CLAUDE_BASE_URL
  const DEFAULT_FONT_NAMES: typeof import('../lib/fontLoader').DEFAULT_FONT_NAMES
  const DEFAULT_GIT_SYNC_INTERVAL: typeof import('../lib/git-sync-contract').DEFAULT_GIT_SYNC_INTERVAL
  const DEFAULT_OPENAI_BASE_URL: typeof import('../lib/ai-provider/index').DEFAULT_OPENAI_BASE_URL
  const DEFAULT_WATERMARK_CONFIG: typeof import('../lib/imageExport/index').DEFAULT_WATERMARK_CONFIG
  const DiskWriteError: typeof import('../lib/diskWriteError').DiskWriteError
  const EDITOR_UI_SCALE_CHANGE_EVENT: typeof import('../lib/appearance').EDITOR_UI_SCALE_CHANGE_EVENT
  const ELECTRON_MAX_FILE_ATTACHMENT_SIZE: typeof import('../lib/fileStorage').ELECTRON_MAX_FILE_ATTACHMENT_SIZE
  const FIXED_APP_SHORTCUT_IDS: typeof import('../lib/fixed-app-shortcuts').FIXED_APP_SHORTCUT_IDS
  const FIXED_CLOSE_SHORTCUT: typeof import('../lib/fixed-app-shortcuts').FIXED_CLOSE_SHORTCUT
  const FIXED_SPLIT_SHORTCUTS: typeof import('../lib/fixed-app-shortcuts').FIXED_SPLIT_SHORTCUTS
  const GLM_BASE_URL: typeof import('../lib/ai-provider/index').GLM_BASE_URL
  const GOOSE_FAVORITE_KEY: typeof import('../lib/local-frontmatter').GOOSE_FAVORITE_KEY
  const GOOSE_FONT_KEY: typeof import('../lib/local-frontmatter').GOOSE_FONT_KEY
  const GOOSE_LAYOUT_KEY: typeof import('../lib/local-frontmatter').GOOSE_LAYOUT_KEY
  const GOOSE_LOCKED_KEY: typeof import('../lib/local-frontmatter').GOOSE_LOCKED_KEY
  const GOOSE_PINNED_KEY: typeof import('../lib/local-frontmatter').GOOSE_PINNED_KEY
  const GitSyncPreparation: typeof import('../lib/git-sync-preparation').GitSyncPreparation
  const IMAGE_EXPORT_LIVE_PREVIEW_MIN_WIDTH: typeof import('../lib/imageExport/index').IMAGE_EXPORT_LIVE_PREVIEW_MIN_WIDTH
  const IMAGE_EXPORT_OPTIONS_CORNER_MIN_WIDTH: typeof import('../lib/imageExport/index').IMAGE_EXPORT_OPTIONS_CORNER_MIN_WIDTH
  const INTERNAL_ASSET_REF_PREFIXES: typeof import('../lib/internalAssetRef').INTERNAL_ASSET_REF_PREFIXES
  const LOCAL_FOLDER_EDITOR_CANDIDATES: typeof import('../lib/local-folder-open-apps').LOCAL_FOLDER_EDITOR_CANDIDATES
  const LOCAL_FOLDER_FILE_MANAGER_CANDIDATES: typeof import('../lib/local-folder-open-apps').LOCAL_FOLDER_FILE_MANAGER_CANDIDATES
  const LOCAL_FOLDER_FILE_SHORTCUTS: typeof import('../lib/local-folder-file-actions').LOCAL_FOLDER_FILE_SHORTCUTS
  const LOCAL_FOLDER_TERMINAL_CANDIDATES: typeof import('../lib/local-folder-open-apps').LOCAL_FOLDER_TERMINAL_CANDIDATES
  const LOCAL_PAGE_FRONTMATTER_SETTINGS_KEYS: typeof import('../lib/local-frontmatter').LOCAL_PAGE_FRONTMATTER_SETTINGS_KEYS
  const MAX_FILE_ATTACHMENT_SIZE: typeof import('../lib/fileStorage').MAX_FILE_ATTACHMENT_SIZE
  const MINIMAX_BASE_URL: typeof import('../lib/ai-provider/index').MINIMAX_BASE_URL
  const NON_CUSTOMIZABLE_APP_SHORTCUT_IDS: typeof import('../lib/fixed-app-shortcuts').NON_CUSTOMIZABLE_APP_SHORTCUT_IDS
  const NOTEBOOK_THEME: typeof import('../lib/imageExport/index').NOTEBOOK_THEME
  const ONBOARDING_CHILD_PAGE_CONTENT: typeof import('../lib/onboarding').ONBOARDING_CHILD_PAGE_CONTENT
  const ONBOARDING_PAGE_CONTENT: typeof import('../lib/onboarding').ONBOARDING_PAGE_CONTENT
  const ONBOARDING_SECOND_CHILD_CONTENT: typeof import('../lib/onboarding').ONBOARDING_SECOND_CHILD_CONTENT
  const ONBOARDING_THIRD_CHILD_CONTENT: typeof import('../lib/onboarding').ONBOARDING_THIRD_CHILD_CONTENT
  const OPEN_DIALOG_SELECTOR: typeof import('../lib/escape-close').OPEN_DIALOG_SELECTOR
  const OPEN_ESCAPE_LAYER_SELECTOR: typeof import('../lib/escape-close').OPEN_ESCAPE_LAYER_SELECTOR
  const OPEN_TOAST_SELECTOR: typeof import('../lib/escape-close').OPEN_TOAST_SELECTOR
  const PUBLIC_RELEASES_API_URL: typeof import('../lib/appUpdateRelease').PUBLIC_RELEASES_API_URL
  const PUBLIC_RELEASES_LATEST_URL: typeof import('../lib/appUpdateRelease').PUBLIC_RELEASES_LATEST_URL
  const PUBLIC_RELEASES_REPO: typeof import('../lib/appUpdateRelease').PUBLIC_RELEASES_REPO
  const PUBLIC_UPDATE_URL: typeof import('../lib/appUpdateRelease').PUBLIC_UPDATE_URL
  const REMOTE_FONT_SOURCES: typeof import('../lib/fontLoader').REMOTE_FONT_SOURCES
  const REMOVED_APP_SHORTCUT_IDS: typeof import('../lib/fixed-app-shortcuts').REMOVED_APP_SHORTCUT_IDS
  const SYSTEM_FONT_STACK: typeof import('../lib/fontLoader').SYSTEM_FONT_STACK
  const activateNotebook: typeof import('../lib/notebookNavigation').activateNotebook
  const applyAccentColor: typeof import('../lib/accentColor').applyAccentColor
  const applyAppearanceScaleVariables: typeof import('../lib/appearance').applyAppearanceScaleVariables
  const applyFontVariables: typeof import('../lib/fontLoader').applyFontVariables
  const applyFrontmatterBodyToContent: typeof import('../lib/local-frontmatter').applyFrontmatterBodyToContent
  const applyTrailingNewlineStyle: typeof import('../lib/local-md-snapshot').applyTrailingNewlineStyle
  const assignExistingStableId: typeof import('../lib/local-page-idmap').assignExistingStableId
  const blobToBase64: typeof import('../lib/imageProcessor').blobToBase64
  const blocksToHTML: typeof import('../lib/export/index').blocksToHTML
  const blocksToMarkdown: typeof import('../lib/export/index').blocksToMarkdown
  const buildLocalFolderPickerItems: typeof import('../lib/local-folder-target').buildLocalFolderPickerItems
  const buildLocalPageId: typeof import('../lib/local-folder-scanner').buildLocalPageId
  const buildNotebookCardTheme: typeof import('../lib/imageExport/index').buildNotebookCardTheme
  const buildSinglePageExport: typeof import('../lib/export/index').buildSinglePageExport
  const canonicalLocalPath: typeof import('../lib/canonicalLocalPath').canonicalLocalPath
  const canonicalRelativePath: typeof import('../lib/canonicalLocalPath').canonicalRelativePath
  const cleanAssetDestination: typeof import('../lib/local-folder-asset-maintenance').cleanAssetDestination
  const clearAllLocalMdSnapshots: typeof import('../lib/local-md-snapshot').clearAllLocalMdSnapshots
  const clearLocalFolderFileDropTarget: typeof import('../lib/local-folder-file-drop-target').clearLocalFolderFileDropTarget
  const clearStartupSettling: typeof import('../lib/appearance').clearStartupSettling
  const closeAllOverlays: typeof import('../lib/closeAllOverlays').closeAllOverlays
  const compareSemver: typeof import('../lib/appUpdateRelease').compareSemver
  const comparisonLocalPath: typeof import('../lib/canonicalLocalPath').comparisonLocalPath
  const compressIfNeeded: typeof import('../lib/imageProcessor').compressIfNeeded
  const compressImage: typeof import('../lib/imageProcessor').compressImage
  const computeEditorUiScale: typeof import('../lib/appearance').computeEditorUiScale
  const computeSidebarFontSize: typeof import('../lib/appearance').computeSidebarFontSize
  const computeSidebarRowHeight: typeof import('../lib/appearance').computeSidebarRowHeight
  const computeUiFontSize: typeof import('../lib/appearance').computeUiFontSize
  const consumeDiskWriteFailure: typeof import('../lib/diskWriteError').consumeDiskWriteFailure
  const convertImageBlobToPng: typeof import('../lib/imageProcessor').convertImageBlobToPng
  const copyLocalFolderPagePath: typeof import('../lib/local-folder-file-actions').copyLocalFolderPagePath
  const currentLocalNotebookRoot: typeof import('../lib/currentLocalPagePath').currentLocalNotebookRoot
  const currentLocalPagePath: typeof import('../lib/currentLocalPagePath').currentLocalPagePath
  const decodeUnsupportedMarkdownForDisk: typeof import('../lib/markdown-raw-guard').decodeUnsupportedMarkdownForDisk
  const deleteLocalMdSnapshot: typeof import('../lib/local-md-snapshot').deleteLocalMdSnapshot
  const describeDiskWriteError: typeof import('../lib/diskWriteError').describeDiskWriteError
  const encodeUnsupportedMarkdownForEditor: typeof import('../lib/markdown-raw-guard').encodeUnsupportedMarkdownForEditor
  const ensureEditorFontAvailable: typeof import('../lib/fontLoader').ensureEditorFontAvailable
  const ensureFilenameAsTitle: typeof import('../lib/local-title-binding').ensureFilenameAsTitle
  const ensurePersistentRemoteFont: typeof import('../lib/fontLoader').ensurePersistentRemoteFont
  const exportNotebooks: typeof import('../lib/export/index').exportNotebooks
  const exportPageToImage: typeof import('../lib/imageExport/index').exportPageToImage
  const exportSelectionToImage: typeof import('../lib/imageExport/index').exportSelectionToImage
  const exportToHTML: typeof import('../lib/export/index').exportToHTML
  const exportToImage: typeof import('../lib/imageExport/index').exportToImage
  const exportToJSON: typeof import('../lib/export/index').exportToJSON
  const exportToMarkdown: typeof import('../lib/export/index').exportToMarkdown
  const exportToPDF: typeof import('../lib/export/index').exportToPDF
  const exportToWord: typeof import('../lib/docxExport/index').exportToWord
  const extractAssetReferencesFromMarkdown: typeof import('../lib/local-folder-asset-maintenance').extractAssetReferencesFromMarkdown
  const extractFirstHeadingText: typeof import('../lib/local-title-binding').extractFirstHeadingText
  const extractFrontmatter: typeof import('../lib/markdown-raw-guard').extractFrontmatter
  const fetchCustomAIModels: typeof import('../lib/ai-provider/index').fetchCustomAIModels
  const fileStorage: typeof import('../lib/fileStorage').fileStorage
  const formatAttachmentSize: typeof import('../lib/fileStorage').formatAttachmentSize
  const formatDualShortcut: typeof import('../lib/onboardingContent').formatDualShortcut
  const formatDualShortcutGroup: typeof import('../lib/onboardingContent').formatDualShortcutGroup
  const formatLocalFolderOpenAppName: typeof import('../lib/local-folder-open-apps').formatLocalFolderOpenAppName
  const frontmatterBodyHasUserVisibleKeys: typeof import('../lib/local-frontmatter').frontmatterBodyHasUserVisibleKeys
  const generateDocxBuffer: typeof import('../lib/docxExport/index').generateDocxBuffer
  const generateExportZip: typeof import('../lib/export/index').generateExportZip
  const getAIAvailability: typeof import('../lib/ai-provider/index').getAIAvailability
  const getAIProviderPreset: typeof import('../lib/ai-provider/index').getAIProviderPreset
  const getApiKeyMissingMessage: typeof import('../lib/ai-provider/index').getApiKeyMissingMessage
  const getAttachmentBadgeLabel: typeof import('../lib/fileStorage').getAttachmentBadgeLabel
  const getCardTheme: typeof import('../lib/imageExport/index').getCardTheme
  const getContentFrontmatterBody: typeof import('../lib/local-frontmatter').getContentFrontmatterBody
  const getCustomAIApiKey: typeof import('../lib/ai-provider/index').getCustomAIApiKey
  const getCustomAIBaseURL: typeof import('../lib/ai-provider/index').getCustomAIBaseURL
  const getDefaultCustomAIBaseURL: typeof import('../lib/ai-provider/index').getDefaultCustomAIBaseURL
  const getEditorFontFamilies: typeof import('../lib/fontLoader').getEditorFontFamilies
  const getFileUploadAvailability: typeof import('../lib/fileUploadAvailability').getFileUploadAvailability
  const getFixedAppShortcuts: typeof import('../lib/fixed-app-shortcuts').getFixedAppShortcuts
  const getImageFromClipboard: typeof import('../lib/imageProcessor').getImageFromClipboard
  const getLocalAssetKind: typeof import('../lib/local-folder-asset-maintenance').getLocalAssetKind
  const getLocalFolderFileDropTarget: typeof import('../lib/local-folder-file-drop-target').getLocalFolderFileDropTarget
  const getLocalMdSnapshot: typeof import('../lib/local-md-snapshot').getLocalMdSnapshot
  const getMaxFileAttachmentSize: typeof import('../lib/fileStorage').getMaxFileAttachmentSize
  const getPageContainingFolderId: typeof import('../lib/local-folder-target').getPageContainingFolderId
  const getPageParentDirectoryId: typeof import('../lib/local-folder-target').getPageParentDirectoryId
  const getProviderCredentialSlots: typeof import('../lib/ai-provider/index').getProviderCredentialSlots
  const getProviderFixedBaseURL: typeof import('../lib/ai-provider/index').getProviderFixedBaseURL
  const getSettingsProviderId: typeof import('../lib/ai-provider/index').getSettingsProviderId
  const getStoredAIModelOptions: typeof import('../lib/ai-provider/index').getStoredAIModelOptions
  const hasCurrentLocalFolderPage: typeof import('../lib/local-folder-file-actions').hasCurrentLocalFolderPage
  const holdGitSyncWrites: typeof import('../lib/git-sync-write-barrier').holdGitSyncWrites
  const importFile: typeof import('../lib/export/index').importFile
  const importFromJSON: typeof import('../lib/export/index').importFromJSON
  const importFromMarkdown: typeof import('../lib/export/index').importFromMarkdown
  const importMarkdownFragment: typeof import('../lib/export/index').importMarkdownFragment
  const importNotebooksFromZip: typeof import('../lib/export/index').importNotebooksFromZip
  const importTextFilesToLocalFolder: typeof import('../lib/local-folder-import').importTextFilesToLocalFolder
  const inferProviderIdFromSettings: typeof import('../lib/ai-provider/index').inferProviderIdFromSettings
  const inspectNotebookImportZip: typeof import('../lib/export/index').inspectNotebookImportZip
  const installAssetMaintenanceSnapshotResponder: typeof import('../lib/asset-maintenance-snapshot').installAssetMaintenanceSnapshotResponder
  const installGitSyncResponder: typeof import('../lib/git-sync-responder').installGitSyncResponder
  const isAIProviderId: typeof import('../lib/ai-provider/index').isAIProviderId
  const isCanonicalPathInside: typeof import('../lib/canonicalLocalPath').isCanonicalPathInside
  const isDeepSeekProModel: typeof import('../lib/ai-provider/index').isDeepSeekProModel
  const isDescendantPage: typeof import('../lib/local-folder-target').isDescendantPage
  const isDiskContentMatchingSnapshot: typeof import('../lib/local-md-snapshot').isDiskContentMatchingSnapshot
  const isElectronHost: typeof import('../lib/local-vault').isElectronHost
  const isExternalFileDrag: typeof import('../lib/local-folder-target').isExternalFileDrag
  const isGithubDownloadUrl: typeof import('../lib/appUpdateRelease').isGithubDownloadUrl
  const isGooseFrontmatterKey: typeof import('../lib/local-frontmatter').isGooseFrontmatterKey
  const isInternalAssetRef: typeof import('../lib/internalAssetRef').isInternalAssetRef
  const isLocalFontAvailable: typeof import('../lib/fontLoader').isLocalFontAvailable
  const isLocalMdUnchanged: typeof import('../lib/local-md-snapshot').isLocalMdUnchanged
  const isLocalPageFrontmatterSettingsUpdate: typeof import('../lib/local-frontmatter').isLocalPageFrontmatterSettingsUpdate
  const isPathInsideNotebookRoot: typeof import('../lib/currentLocalPagePath').isPathInsideNotebookRoot
  const isReservedCloseOrSplitShortcut: typeof import('../lib/fixed-app-shortcuts').isReservedCloseOrSplitShortcut
  const isStatMatchingSnapshot: typeof import('../lib/local-md-snapshot').isStatMatchingSnapshot
  const isSupportedTextImportFile: typeof import('../lib/local-folder-import').isSupportedTextImportFile
  const isValidImageUrl: typeof import('../lib/imageProcessor').isValidImageUrl
  const jsonContentToMarkdown: typeof import('../lib/export/index').jsonContentToMarkdown
  const localAssetPaths: typeof import('../lib/local-folder-asset-maintenance').localAssetPaths
  const localFileTitleFromPath: typeof import('../lib/local-folder-scanner').localFileTitleFromPath
  const localPathsAreCaseInsensitive: typeof import('../lib/canonicalLocalPath').localPathsAreCaseInsensitive
  const markSelfWrite: typeof import('../lib/local-md-snapshot').markSelfWrite
  const markStartupSettling: typeof import('../lib/appearance').markStartupSettling
  const markUserInteraction: typeof import('../lib/editor-interaction-signal').markUserInteraction
  const materializeImageBlob: typeof import('../lib/imageProcessor').materializeImageBlob
  const mergeLocalPageSettingsIntoFrontmatter: typeof import('../lib/local-frontmatter').mergeLocalPageSettingsIntoFrontmatter
  const mergeSettingsIntoFrontmatterHeader: typeof import('../lib/local-frontmatter').mergeSettingsIntoFrontmatterHeader
  const migrateLocalPageIdMapEntry: typeof import('../lib/local-page-idmap').migrateLocalPageIdMapEntry
  const normalizeCardThemeId: typeof import('../lib/imageExport/index').normalizeCardThemeId
  const normalizeLocalFontName: typeof import('../lib/fontLoader').normalizeLocalFontName
  const normalizeLocalPathSlashes: typeof import('../lib/canonicalLocalPath').normalizeLocalPathSlashes
  const normalizePageLayout: typeof import('../lib/local-frontmatter').normalizePageLayout
  const normalizeWatermarkConfig: typeof import('../lib/imageExport/index').normalizeWatermarkConfig
  const normalizedGitRemote: typeof import('../lib/git-sync-contract').normalizedGitRemote
  const onboardingChildPageContent: typeof import('../lib/onboardingContent').onboardingChildPageContent
  const onboardingPageContent: typeof import('../lib/onboardingContent').onboardingPageContent
  const openLocalFolderPageInExternalApp: typeof import('../lib/local-folder-file-actions').openLocalFolderPageInExternalApp
  const openLocalFolderPageInTerminal: typeof import('../lib/local-folder-file-actions').openLocalFolderPageInTerminal
  const pageDirectory: typeof import('../lib/currentLocalPagePath').pageDirectory
  const pageHasLocalSidecarAttachments: typeof import('../lib/export/index').pageHasLocalSidecarAttachments
  const pageSettingsFromMarkdown: typeof import('../lib/local-frontmatter').pageSettingsFromMarkdown
  const parseLocalFrontmatterBlob: typeof import('../lib/local-frontmatter').parseLocalFrontmatterBlob
  const parseLocalMarkdownContent: typeof import('../lib/local-folder-scanner').parseLocalMarkdownContent
  const parseReleaseTag: typeof import('../lib/appUpdateRelease').parseReleaseTag
  const pickUpdateAsset: typeof import('../lib/appUpdateRelease').pickUpdateAsset
  const pruneLocalPageIdMap: typeof import('../lib/local-page-idmap').pruneLocalPageIdMap
  const readLocalPageIdMap: typeof import('../lib/local-page-idmap').readLocalPageIdMap
  const readPersistentDismissState: typeof import('../lib/dismiss-state').readPersistentDismissState
  const readRecentLocalFolderTargets: typeof import('../lib/local-folder-target').readRecentLocalFolderTargets
  const registerEscapeClose: typeof import('../lib/escape-close').registerEscapeClose
  const releaseGitSyncWrites: typeof import('../lib/git-sync-write-barrier').releaseGitSyncWrites
  const releaseStartupSettlingAfterPaint: typeof import('../lib/appearance').releaseStartupSettlingAfterPaint
  const rememberDiskWriteFailure: typeof import('../lib/diskWriteError').rememberDiskWriteFailure
  const rememberLocalFolderTarget: typeof import('../lib/local-folder-target').rememberLocalFolderTarget
  const removeLocalPageIdMap: typeof import('../lib/local-page-idmap').removeLocalPageIdMap
  const renderExportHtml: typeof import('../lib/export/index').renderExportHtml
  const renderPageToDocxBlob: typeof import('../lib/docxExport/index').renderPageToDocxBlob
  const resolveAccentRuntimeTokens: typeof import('../lib/accentColor').resolveAccentRuntimeTokens
  const resolveActiveProtocol: typeof import('../lib/ai-provider/index').resolveActiveProtocol
  const resolveCardTheme: typeof import('../lib/imageExport/index').resolveCardTheme
  const resolveCurrentLocalFolderPage: typeof import('../lib/local-folder-file-actions').resolveCurrentLocalFolderPage
  const resolveDropTargetParentId: typeof import('../lib/local-folder-target').resolveDropTargetParentId
  const resolveImportParentForDrop: typeof import('../lib/local-folder-import').resolveImportParentForDrop
  const resolveLocalFolderImportParentId: typeof import('../lib/local-folder-target').resolveLocalFolderImportParentId
  const resolveNotebookLandingPageId: typeof import('../lib/notebookNavigation').resolveNotebookLandingPageId
  const resolveOrCreateStableId: typeof import('../lib/local-page-idmap').resolveOrCreateStableId
  const resolveProtocolForProvider: typeof import('../lib/ai-provider/index').resolveProtocolForProvider
  const restoreMissingReferencedLocalAssets: typeof import('../lib/local-folder-asset-maintenance').restoreMissingReferencedLocalAssets
  const revealLocalFolderPageInFileManager: typeof import('../lib/local-folder-file-actions').revealLocalFolderPageInFileManager
  const runAIText: typeof import('../lib/ai-provider/index').runAIText
  const runAITextStream: typeof import('../lib/ai-provider/index').runAITextStream
  const sanitizeFileName: typeof import('../lib/fileStorage').sanitizeFileName
  const sanitizeFilenameSegment: typeof import('../lib/local-title-binding').sanitizeFilenameSegment
  const saveBlobAndReveal: typeof import('../lib/export/index').saveBlobAndReveal
  const scanLocalFolderPages: typeof import('../lib/local-folder-scanner').scanLocalFolderPages
  const scanUnreferencedLocalAssets: typeof import('../lib/local-folder-asset-maintenance').scanUnreferencedLocalAssets
  const setLocalFolderFileDropTarget: typeof import('../lib/local-folder-file-drop-target').setLocalFolderFileDropTarget
  const setLocalMdSnapshot: typeof import('../lib/local-md-snapshot').setLocalMdSnapshot
  const shouldIgnoreEntry: typeof import('../lib/local-folder-scanner').shouldIgnoreEntry
  const shouldIgnoreLocalRelativePath: typeof import('../lib/local-folder-scanner').shouldIgnoreLocalRelativePath
  const shouldShowImageExportLivePreview: typeof import('../lib/imageExport/index').shouldShowImageExportLivePreview
  const shouldShowImageExportOptionsCorner: typeof import('../lib/imageExport/index').shouldShowImageExportOptionsCorner
  const splitFilePath: typeof import('../lib/local-title-binding').splitFilePath
  const stripSystemVolumesDataPrefix: typeof import('../lib/canonicalLocalPath').stripSystemVolumesDataPrefix
  const syncAccentColorCssVars: typeof import('../lib/accentColor').syncAccentColorCssVars
  const toCssFontFamily: typeof import('../lib/fontLoader').toCssFontFamily
  const toDiskWriteError: typeof import('../lib/diskWriteError').toDiskWriteError
  const toRelativePath: typeof import('../lib/local-page-idmap').toRelativePath
  const unknownGitVisibility: typeof import('../lib/git-sync-contract').unknownGitVisibility
  const updateSnapshotAfterWrite: typeof import('../lib/local-md-snapshot').updateSnapshotAfterWrite
  const updateSnapshotStat: typeof import('../lib/local-md-snapshot').updateSnapshotStat
  const validateGitRepository: typeof import('../lib/git-sync-contract').validateGitRepository
  const validateGitSyncConfig: typeof import('../lib/git-sync-contract').validateGitSyncConfig
  const validateRepositoryId: typeof import('../lib/git-sync-contract').validateRepositoryId
  const waitForFonts: typeof import('../lib/fontLoader').waitForFonts
  const waitForGitSyncWrites: typeof import('../lib/git-sync-write-barrier').waitForGitSyncWrites
  const wasRecentlyInteracting: typeof import('../lib/editor-interaction-signal').wasRecentlyInteracting
  const wasRecentlySelfWritten: typeof import('../lib/local-md-snapshot').wasRecentlySelfWritten
  const writeLocalPageIdMap: typeof import('../lib/local-page-idmap').writeLocalPageIdMap
  const writePersistentDismissState: typeof import('../lib/dismiss-state').writePersistentDismissState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AIMessage, AIModelOption, AIProviderId, AIProviderIdLike, AIProviderPreset, AIReasoningLevel, AIRequestOverrides, AISettingsLike, AIStreamPhase, AIStreamUpdate, CustomAIProtocol, RunAITextOptions, RunAITextStreamOptions } from '../lib/ai-provider/index'
  import('../lib/ai-provider/index')
  // @ts-ignore
  export type { GithubReleaseAsset, ParsedReleaseVersion } from '../lib/appUpdateRelease'
  import('../lib/appUpdateRelease')
  // @ts-ignore
  export type { AssetAppearance, AssetMaintenanceBridge, AssetNotebook, AssetScan, AssetWorkspaceSnapshot } from '../lib/asset-maintenance-contract'
  import('../lib/asset-maintenance-contract')
  // @ts-ignore
  export type { DiskWriteError } from '../lib/diskWriteError'
  import('../lib/diskWriteError')
  // @ts-ignore
  export type { FixedAppShortcutId } from '../lib/fixed-app-shortcuts'
  import('../lib/fixed-app-shortcuts')
  // @ts-ignore
  export type { GitRepositoryConfig, GitRepositoryFolder, GitRepositoryInput, GitRepositoryVisibility, GitSyncBridge, GitSyncConfig, GitSyncProvider, GitSyncState, GitSyncStatus, GitVisibilityCheck } from '../lib/git-sync-contract'
  import('../lib/git-sync-contract')
  // @ts-ignore
  export type { GitSyncPreparation, GitSyncPreparationRequest } from '../lib/git-sync-preparation'
  import('../lib/git-sync-preparation')
  // @ts-ignore
  export type { CardTheme, CardThemeId, NotebookCardThemeContext, WatermarkConfig } from '../lib/imageExport/index'
  import('../lib/imageExport/index')
  // @ts-ignore
  export type { AssetMaintenanceFs, RestoreMissingLocalAssetsResult, UnreferencedLocalAsset } from '../lib/local-folder-asset-maintenance'
  import('../lib/local-folder-asset-maintenance')
  // @ts-ignore
  export type { LocalFolderOpenAppCandidate, LocalFolderOpenAppKind } from '../lib/local-folder-open-apps'
  import('../lib/local-folder-open-apps')
  // @ts-ignore
  export type { ParsedLocalMarkdown } from '../lib/local-folder-scanner'
  import('../lib/local-folder-scanner')
  // @ts-ignore
  export type { LocalFolderPickerItem, LocalFolderTargetKey } from '../lib/local-folder-target'
  import('../lib/local-folder-target')
  // @ts-ignore
  export type { LocalPageFrontmatterSettings, LocalPageFrontmatterSettingsKey, MergeFrontmatterResult } from '../lib/local-frontmatter'
  import('../lib/local-frontmatter')
  // @ts-ignore
  export type { LocalMdFileStat } from '../lib/local-md-snapshot'
  import('../lib/local-md-snapshot')
  // @ts-ignore
  export type { LocalPageIdMap } from '../lib/local-page-idmap'
  import('../lib/local-page-idmap')
}
