// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const EDITOR_ONLY_FIXED_SHORTCUTS: typeof import('../lib/shortcut-platform').EDITOR_ONLY_FIXED_SHORTCUTS
  const ELECTRON_MAX_VIDEO_ATTACHMENT_SIZE: typeof import('../lib/videoStorage').ELECTRON_MAX_VIDEO_ATTACHMENT_SIZE
  const MAX_VIDEO_ATTACHMENT_SIZE: typeof import('../lib/videoStorage').MAX_VIDEO_ATTACHMENT_SIZE
  const SIDEBAR_PAGE_LIST_SELECTOR: typeof import('../lib/sidebarListCollapse').SIDEBAR_PAGE_LIST_SELECTOR
  const TEXT_COLORS: typeof import('../lib/textColors').TEXT_COLORS
  const VIDEO_OUTPUT_MIME: typeof import('../lib/videoProcessor').VIDEO_OUTPUT_MIME
  const WORKSPACE_COLLAPSE_LEFT_BELOW: typeof import('../lib/workspaceViewport').WORKSPACE_COLLAPSE_LEFT_BELOW
  const WORKSPACE_COLLAPSE_RIGHT_BELOW: typeof import('../lib/workspaceViewport').WORKSPACE_COLLAPSE_RIGHT_BELOW
  const WORKSPACE_MIN_MAIN_WIDTH: typeof import('../lib/workspaceViewport').WORKSPACE_MIN_MAIN_WIDTH
  const WORKSPACE_MIN_WINDOW_HEIGHT: typeof import('../lib/workspaceViewport').WORKSPACE_MIN_WINDOW_HEIGHT
  const WORKSPACE_MIN_WINDOW_WIDTH: typeof import('../lib/workspaceViewport').WORKSPACE_MIN_WINDOW_WIDTH
  const activateWorkspace: typeof import('../lib/settings-navigation').activateWorkspace
  const applyRolldownPolyfills: typeof import('../lib/rolldown-polyfill').applyRolldownPolyfills
  const areSetupGuideAIConnectionsEqual: typeof import('../lib/setupGuideAI').areSetupGuideAIConnectionsEqual
  const armSidebarListCollapse: typeof import('../lib/sidebarListCollapse').armSidebarListCollapse
  const canTestSetupGuideAI: typeof import('../lib/setupGuideAI').canTestSetupGuideAI
  const canonicalizeRecordedShortcut: typeof import('../lib/shortcut-platform').canonicalizeRecordedShortcut
  const clearWorkspaceStartupSelection: typeof import('../lib/workspaceStartup').clearWorkspaceStartupSelection
  const cn: typeof import('../lib/utils').cn
  const collapseAllSidebarExpandedPages: typeof import('../lib/sidebarListCollapse').collapseAllSidebarExpandedPages
  const collectSidebarRevealAncestorIds: typeof import('../lib/sidebarListCollapse').collectSidebarRevealAncestorIds
  const completePageTitleFocus: typeof import('../lib/page-title-focus').completePageTitleFocus
  const computeSidebarEscapeExpandedIds: typeof import('../lib/sidebarListCollapse').computeSidebarEscapeExpandedIds
  const computeWorkspaceViewportCollapse: typeof import('../lib/workspaceViewport').computeWorkspaceViewportCollapse
  const consumePendingAssociatedMarkdownFiles: typeof import('../lib/openAssociatedMarkdown').consumePendingAssociatedMarkdownFiles
  const deletePageWithUndo: typeof import('../lib/page-delete-actions').deletePageWithUndo
  const deleteWebdavBackup: typeof import('../lib/webdavSync').deleteWebdavBackup
  const documentTextColors: typeof import('../lib/textColors').documentTextColors
  const downloadWebdavBackup: typeof import('../lib/webdavSync').downloadWebdavBackup
  const effectiveSingleTabMode: typeof import('../lib/tabMode').effectiveSingleTabMode
  const findContainingLocalFolderNotebook: typeof import('../lib/openAssociatedMarkdown').findContainingLocalFolderNotebook
  const flushLocalStorageWrites: typeof import('../lib/storage').flushLocalStorageWrites
  const formatShortcut: typeof import('../lib/utils').formatShortcut
  const formatShortcutToken: typeof import('../lib/shortcut-platform').formatShortcutToken
  const formatSystemModifier: typeof import('../lib/shortcut-platform').formatSystemModifier
  const getDbStorageItem: typeof import('../lib/storage').getDbStorageItem
  const getModifierOnlyShortcut: typeof import('../lib/shortcut-match').getModifierOnlyShortcut
  const getPlatformKind: typeof import('../lib/utils').getPlatformKind
  const getPrimaryModifierKeyDisplay: typeof import('../lib/utils').getPrimaryModifierKeyDisplay
  const getPrimaryModifierKeyLabel: typeof import('../lib/utils').getPrimaryModifierKeyLabel
  const getSetupGuideAIStatus: typeof import('../lib/setupGuideAI').getSetupGuideAIStatus
  const getShortcutFromMouseEvent: typeof import('../lib/shortcut-match').getShortcutFromMouseEvent
  const hasSidebarListEscapeOverlay: typeof import('../lib/sidebarListCollapse').hasSidebarListEscapeOverlay
  const hasValidSetupGuideAIResponse: typeof import('../lib/setupGuideAI').hasValidSetupGuideAIResponse
  const isBackupFileName: typeof import('../lib/webdavSync').isBackupFileName
  const isEffectiveRightSidePanelOpen: typeof import('../lib/workspaceViewport').isEffectiveRightSidePanelOpen
  const isEffectiveSidebarCollapsed: typeof import('../lib/workspaceViewport').isEffectiveSidebarCollapsed
  const isElectronLocalFolderDirectory: typeof import('../lib/sidebarPageNavigation').isElectronLocalFolderDirectory
  const isHotkeyAllowedInSettings: typeof import('../lib/settings-navigation').isHotkeyAllowedInSettings
  const isLocalFolderDirectoryPage: typeof import('../lib/sidebarPageNavigation').isLocalFolderDirectoryPage
  const isMacPlatform: typeof import('../lib/utils').isMacPlatform
  const isPageTitleAutoFocusProtected: typeof import('../lib/page-title-focus').isPageTitleAutoFocusProtected
  const isPageTitleFocusRequested: typeof import('../lib/page-title-focus').isPageTitleFocusRequested
  const isPinyinQuery: typeof import('../lib/pinyin-search').isPinyinQuery
  const isPlatformPrimaryModifierEvent: typeof import('../lib/shortcut-platform').isPlatformPrimaryModifierEvent
  const isRandomPageIcon: typeof import('../lib/randomPageIcon').isRandomPageIcon
  const isSettingsTab: typeof import('../lib/settings-navigation').isSettingsTab
  const isSetupGuideAIRequestCurrent: typeof import('../lib/setupGuideAI').isSetupGuideAIRequestCurrent
  const isSetupGuideVisible: typeof import('../lib/setupGuide').isSetupGuideVisible
  const isSidebarListCollapseArmed: typeof import('../lib/sidebarListCollapse').isSidebarListCollapseArmed
  const isSidebarPageListTarget: typeof import('../lib/sidebarListCollapse').isSidebarPageListTarget
  const isUnsavedLocalPage: typeof import('../lib/unsavedLocalPage').isUnsavedLocalPage
  const isVideoUploadFile: typeof import('../lib/videoProcessor').isVideoUploadFile
  const isWikiMediaTarget: typeof import('../lib/wikiLink').isWikiMediaTarget
  const isWorkspaceNavigationHotkey: typeof import('../lib/settings-navigation').isWorkspaceNavigationHotkey
  const isWorkspaceSettingsOpen: typeof import('../lib/settings-navigation').isWorkspaceSettingsOpen
  const listWebdavBackups: typeof import('../lib/webdavSync').listWebdavBackups
  const localPageHasPersistableContent: typeof import('../lib/unsavedLocalPage').localPageHasPersistableContent
  const localStorageAdapter: typeof import('../lib/storage').localStorageAdapter
  const markAssociatedMarkdownOpened: typeof import('../lib/workspaceStartup').markAssociatedMarkdownOpened
  const matchModifierOnlyShortcutKey: typeof import('../lib/shortcut-match').matchModifierOnlyShortcutKey
  const matchModifierOnlyShortcutKeyDown: typeof import('../lib/shortcut-match').matchModifierOnlyShortcutKeyDown
  const matchMouseShortcut: typeof import('../lib/shortcut-match').matchMouseShortcut
  const matchShortcut: typeof import('../lib/shortcut-match').matchShortcut
  const normalizeBaseUrl: typeof import('../lib/webdavSync').normalizeBaseUrl
  const normalizeExternalUrl: typeof import('../lib/openExternalUrl').normalizeExternalUrl
  const normalizeRemoteDir: typeof import('../lib/webdavSync').normalizeRemoteDir
  const normalizeShortcutForConflict: typeof import('../lib/shortcut-platform').normalizeShortcutForConflict
  const normalizeShortcutToken: typeof import('../lib/shortcut-platform').normalizeShortcutToken
  const normalizeWikiPath: typeof import('../lib/wikiLink').normalizeWikiPath
  const onboardingSecondChildContent: typeof import('../lib/onboardingContent').onboardingSecondChildContent
  const onboardingThirdChildContent: typeof import('../lib/onboardingContent').onboardingThirdChildContent
  const openAssociatedMarkdownFile: typeof import('../lib/openAssociatedMarkdown').openAssociatedMarkdownFile
  const openAssociatedMarkdownFiles: typeof import('../lib/openAssociatedMarkdown').openAssociatedMarkdownFiles
  const openExternalUrl: typeof import('../lib/openExternalUrl').openExternalUrl
  const openPageFromSidebar: typeof import('../lib/sidebarPageNavigation').openPageFromSidebar
  const parseWikiLinkInner: typeof import('../lib/wikiLink').parseWikiLinkInner
  const permanentlyDeletePageWithCleanup: typeof import('../lib/page-delete-actions').permanentlyDeletePageWithCleanup
  const pickRandomPageIcon: typeof import('../lib/randomPageIcon').pickRandomPageIcon
  const pinyinMatchIndices: typeof import('../lib/pinyin-search').pinyinMatchIndices
  const prepareWorkspaceStartup: typeof import('../lib/workspaceStartup').prepareWorkspaceStartup
  const readDbStorageJSON: typeof import('../lib/storage').readDbStorageJSON
  const redactSetupGuideAIError: typeof import('../lib/setupGuideAI').redactSetupGuideAIError
  const removeDbStorageItem: typeof import('../lib/storage').removeDbStorageItem
  const renderWorkspaceAfterStartup: typeof import('../lib/workspaceStartup').renderWorkspaceAfterStartup
  const requestPageTitleFocus: typeof import('../lib/page-title-focus').requestPageTitleFocus
  const resolveModModifier: typeof import('../lib/shortcut-platform').resolveModModifier
  const resolvePageIcon: typeof import('../lib/resolvePageIcon').resolvePageIcon
  const resolvePageMentionNavigation: typeof import('../lib/pageMentionNavigation').resolvePageMentionNavigation
  const resolveSidebarCollapseTargetId: typeof import('../lib/sidebarListCollapse').resolveSidebarCollapseTargetId
  const resolveWikiLinkTarget: typeof import('../lib/pageMentionNavigation').resolveWikiLinkTarget
  const restoreLastNoteIfNeeded: typeof import('../lib/workspaceStartup').restoreLastNoteIfNeeded
  const restorePageWithToast: typeof import('../lib/page-delete-actions').restorePageWithToast
  const sameSidebarExpandedIds: typeof import('../lib/sidebarListCollapse').sameSidebarExpandedIds
  const serializeWikiLinkMarkdown: typeof import('../lib/wikiLink').serializeWikiLinkMarkdown
  const setDbStorageItem: typeof import('../lib/storage').setDbStorageItem
  const shortcutHasModifier: typeof import('../lib/shortcut-match').shortcutHasModifier
  const shouldCollapseSidebarListOnEscape: typeof import('../lib/sidebarListCollapse').shouldCollapseSidebarListOnEscape
  const shouldPreserveStartupSelection: typeof import('../lib/workspaceStartup').shouldPreserveStartupSelection
  const shouldSuppressSidebarSelect: typeof import('../lib/sidebarPageNavigation').shouldSuppressSidebarSelect
  const stripWikiMarkdownExtension: typeof import('../lib/wikiLink').stripWikiMarkdownExtension
  const subscribePageTitleFocus: typeof import('../lib/page-title-focus').subscribePageTitleFocus
  const testWebdavConnection: typeof import('../lib/webdavSync').testWebdavConnection
  const textColorVariables: typeof import('../lib/textColors').textColorVariables
  const textColorsOnSurface: typeof import('../lib/textColors').textColorsOnSurface
  const transcodeVideo: typeof import('../lib/videoProcessor').transcodeVideo
  const triggerAutoWebdavBackup: typeof import('../lib/webdavSync').triggerAutoWebdavBackup
  const tryCollapseSidebarListOnEscape: typeof import('../lib/sidebarListCollapse').tryCollapseSidebarListOnEscape
  const undoLocalTrash: typeof import('../lib/page-delete-actions').undoLocalTrash
  const uploadWebdavBackup: typeof import('../lib/webdavSync').uploadWebdavBackup
  const useEffectiveSingleTabMode: typeof import('../lib/tabMode').useEffectiveSingleTabMode
  const videoStorage: typeof import('../lib/videoStorage').videoStorage
  const wikiKeysForLocalPath: typeof import('../lib/wikiLink').wikiKeysForLocalPath
  const wikiLinkDisplayTitle: typeof import('../lib/wikiLink').wikiLinkDisplayTitle
  const wikiPathKey: typeof import('../lib/wikiLink').wikiPathKey
  const writeDbStorageJSON: typeof import('../lib/storage').writeDbStorageJSON
}
// for type re-export
declare global {
  // @ts-ignore
  export type { PageMentionNavigationResult } from '../lib/pageMentionNavigation'
  import('../lib/pageMentionNavigation')
  // @ts-ignore
  export type { SetupGuideAIConnection, SetupGuideAIStatus } from '../lib/setupGuideAI'
  import('../lib/setupGuideAI')
  // @ts-ignore
  export type { ModifierShortcut, MouseShortcut } from '../lib/shortcut-match'
  import('../lib/shortcut-match')
  // @ts-ignore
  export type { SidebarCollapsePage } from '../lib/sidebarListCollapse'
  import('../lib/sidebarListCollapse')
  // @ts-ignore
  export type { TextColorTheme } from '../lib/textColors'
  import('../lib/textColors')
  // @ts-ignore
  export type { PlatformKind } from '../lib/utils'
  import('../lib/utils')
  // @ts-ignore
  export type { VideoTranscodeProgress } from '../lib/videoProcessor'
  import('../lib/videoProcessor')
  // @ts-ignore
  export type { WebdavBackupFile } from '../lib/webdavSync'
  import('../lib/webdavSync')
  // @ts-ignore
  export type { ParsedWikiLink } from '../lib/wikiLink'
  import('../lib/wikiLink')
  // @ts-ignore
  export type { LastNoteRestoreResult } from '../lib/workspaceStartup'
  import('../lib/workspaceStartup')
  // @ts-ignore
  export type { WorkspaceViewportCollapse } from '../lib/workspaceViewport'
  import('../lib/workspaceViewport')
}
