// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const ACCENT_COLORS: typeof import('../stores/settings/index').ACCENT_COLORS
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT: typeof import('../stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX: typeof import('../stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN: typeof import('../stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN
  const CONVERSATION_STALE_MS: typeof import('../stores/useNotebookAiChats').CONVERSATION_STALE_MS
  const DEFAULT_ACCENT_COLOR: typeof import('../stores/settings/index').DEFAULT_ACCENT_COLOR
  const DEFAULT_APP_SHORTCUTS: typeof import('../stores/settings/index').DEFAULT_APP_SHORTCUTS
  const DEFAULT_CLOSE_TAB_SHORTCUT: typeof import('../stores/settings/index').DEFAULT_CLOSE_TAB_SHORTCUT
  const DEFAULT_NOTEBOOK: typeof import('../stores/useNotebooks').DEFAULT_NOTEBOOK
  const DEFAULT_QUICKNOTE_HOTKEY: typeof import('../stores/settings/index').DEFAULT_QUICKNOTE_HOTKEY
  const DEFAULT_SEARCH_HOTKEY: typeof import('../stores/settings/index').DEFAULT_SEARCH_HOTKEY
  const DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT: typeof import('../stores/settings/index').DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT
  const DEFAULT_SEARCH_PROVIDERS: typeof import('../stores/settings/index').DEFAULT_SEARCH_PROVIDERS
  const DEFAULT_WAKE_HOTKEY: typeof import('../stores/settings/index').DEFAULT_WAKE_HOTKEY
  const EDITOR_FONT_SIZE_DEFAULT: typeof import('../stores/settings/index').EDITOR_FONT_SIZE_DEFAULT
  const EDITOR_FONT_SIZE_MAX: typeof import('../stores/settings/index').EDITOR_FONT_SIZE_MAX
  const EDITOR_FONT_SIZE_MIN: typeof import('../stores/settings/index').EDITOR_FONT_SIZE_MIN
  const EDITOR_SPLIT_PERSIST_KEY_PREFIX: typeof import('../stores/useEditorSplit').EDITOR_SPLIT_PERSIST_KEY_PREFIX
  const FILE_NAV_AI_PANEL: typeof import('../stores/useFileNavHistory').FILE_NAV_AI_PANEL
  const FILE_NAV_WELCOME: typeof import('../stores/useFileNavHistory').FILE_NAV_WELCOME
  const LOCAL_FOLDER_ROOT_DIR_KEY: typeof import('../stores/localFolderOrder').LOCAL_FOLDER_ROOT_DIR_KEY
  const NOTEBOOK_AI_TAB_PAGE_ID_PREFIX: typeof import('../stores/useTabs').NOTEBOOK_AI_TAB_PAGE_ID_PREFIX
  const QUICKNOTE_DEFAULT_HEIGHT: typeof import('../stores/useQuickNote').QUICKNOTE_DEFAULT_HEIGHT
  const QUICKNOTE_DEFAULT_WIDTH: typeof import('../stores/useQuickNote').QUICKNOTE_DEFAULT_WIDTH
  const QUICKNOTE_MIN_HEIGHT: typeof import('../stores/useQuickNote').QUICKNOTE_MIN_HEIGHT
  const QUICKNOTE_MIN_WIDTH: typeof import('../stores/useQuickNote').QUICKNOTE_MIN_WIDTH
  const QUICKNOTE_SLOTS: typeof import('../stores/useQuickNote').QUICKNOTE_SLOTS
  const QUICKNOTE_SLOT_COUNT: typeof import('../stores/useQuickNote').QUICKNOTE_SLOT_COUNT
  const QUICKNOTE_ZOOM_DEFAULT: typeof import('../stores/useQuickNote').QUICKNOTE_ZOOM_DEFAULT
  const QUICKNOTE_ZOOM_MAX: typeof import('../stores/useQuickNote').QUICKNOTE_ZOOM_MAX
  const QUICKNOTE_ZOOM_MIN: typeof import('../stores/useQuickNote').QUICKNOTE_ZOOM_MIN
  const QUICKNOTE_ZOOM_STEP: typeof import('../stores/useQuickNote').QUICKNOTE_ZOOM_STEP
  const SIDEBAR_FONT_SIZE_DEFAULT: typeof import('../stores/settings/index').SIDEBAR_FONT_SIZE_DEFAULT
  const SIDEBAR_FONT_SIZE_MAX: typeof import('../stores/settings/index').SIDEBAR_FONT_SIZE_MAX
  const SIDEBAR_FONT_SIZE_MIN: typeof import('../stores/settings/index').SIDEBAR_FONT_SIZE_MIN
  const WELCOME_TAB_PAGE_ID: typeof import('../stores/useTabs').WELCOME_TAB_PAGE_ID
  const appendLocalFolderOrderEntries: typeof import('../stores/localFolderOrder').appendLocalFolderOrderEntries
  const applyLocalFolderReorder: typeof import('../stores/localFolderOrder').applyLocalFolderReorder
  const applyPersistedTabSplit: typeof import('../stores/useEditorSplit').applyPersistedTabSplit
  const buildQuickNoteDraftPage: typeof import('../stores/useQuickNote').buildQuickNoteDraftPage
  const clampQuickNoteZoom: typeof import('../stores/useQuickNote').clampQuickNoteZoom
  const clearLocalFolderOrder: typeof import('../stores/localFolderOrder').clearLocalFolderOrder
  const clearLocalPageMetadataCache: typeof import('../stores/pages/index').clearLocalPageMetadataCache
  const composerDraftHasContent: typeof import('../stores/useNotebookAiChats').composerDraftHasContent
  const createDefaultQuickNoteSlotNames: typeof import('../stores/useQuickNote').createDefaultQuickNoteSlotNames
  const createEmptyQuickNoteDrafts: typeof import('../stores/useQuickNote').createEmptyQuickNoteDrafts
  const editorSplitPersistKey: typeof import('../stores/useEditorSplit').editorSplitPersistKey
  const ensureLocalFolderOrdersLoaded: typeof import('../stores/localFolderOrder').ensureLocalFolderOrdersLoaded
  const extractQuickNoteDraftTitle: typeof import('../stores/useQuickNote').extractQuickNoteDraftTitle
  const fileNavKeyForTab: typeof import('../stores/useFileNavHistory').fileNavKeyForTab
  const findTabLeaf: typeof import('../stores/useEditorSplit').findTabLeaf
  const flushEditorContent: typeof import('../stores/pages/index').flushEditorContent
  const flushSidebarViewPersist: typeof import('../stores/useSidebarView').flushSidebarViewPersist
  const getActiveDraftContent: typeof import('../stores/useQuickNote').getActiveDraftContent
  const getLocalFolderOrders: typeof import('../stores/localFolderOrder').getLocalFolderOrders
  const getNotebookAiTabPageId: typeof import('../stores/useTabs').getNotebookAiTabPageId
  const getQuickNoteSlotName: typeof import('../stores/useQuickNote').getQuickNoteSlotName
  const insertLocalFolderOrder: typeof import('../stores/localFolderOrder').insertLocalFolderOrder
  const isNotebookAiTab: typeof import('../stores/useTabs').isNotebookAiTab
  const isQuickNoteDraftEmpty: typeof import('../stores/useQuickNote').isQuickNoteDraftEmpty
  const isSpecialTab: typeof import('../stores/useTabs').isSpecialTab
  const loadQuickNoteSlotNames: typeof import('../stores/useQuickNote').loadQuickNoteSlotNames
  const migrateNotebookAiChatsState: typeof import('../stores/useNotebookAiChats').migrateNotebookAiChatsState
  const pageFileNavKey: typeof import('../stores/useFileNavHistory').pageFileNavKey
  const parseFileNavKey: typeof import('../stores/useFileNavHistory').parseFileNavKey
  const parsePersistedQuickNoteSlotNames: typeof import('../stores/useQuickNote').parsePersistedQuickNoteSlotNames
  const persistQuickNoteSlotNames: typeof import('../stores/useQuickNote').persistQuickNoteSlotNames
  const reassignLocalFolderOrder: typeof import('../stores/localFolderOrder').reassignLocalFolderOrder
  const recoverQuickNoteDrafts: typeof import('../stores/useQuickNote').recoverQuickNoteDrafts
  const removeLocalFolderOrders: typeof import('../stores/localFolderOrder').removeLocalFolderOrders
  const selectExpandedIds: typeof import('../stores/useSidebarView').selectExpandedIds
  const selectFavoritesCollapsed: typeof import('../stores/useSidebarView').selectFavoritesCollapsed
  const selectFocusedId: typeof import('../stores/useSidebarView').selectFocusedId
  const selectSelectedId: typeof import('../stores/useSidebarView').selectSelectedId
  const serializeQuickNoteSlotNames: typeof import('../stores/useQuickNote').serializeQuickNoteSlotNames
  const setLocalFolderOrder: typeof import('../stores/localFolderOrder').setLocalFolderOrder
  const sortLocalFolderChildren: typeof import('../stores/localFolderOrder').sortLocalFolderChildren
  const sortNotebooksByOrder: typeof import('../stores/useNotebooks').sortNotebooksByOrder
  const stripComposerDraftImages: typeof import('../stores/useNotebookAiChats').stripComposerDraftImages
  const toggleSidebarFolder: typeof import('../stores/useSidebarView').toggleSidebarFolder
  const updateQuickNoteSlotName: typeof import('../stores/useQuickNote').updateQuickNoteSlotName
  const useAiStatus: typeof import('../stores/useAiStatus').useAiStatus
  const useEditorSplit: typeof import('../stores/useEditorSplit').useEditorSplit
  const useEditorSplitSelector: typeof import('../stores/useEditorSplit').useEditorSplitSelector
  const useFileNavHistory: typeof import('../stores/useFileNavHistory').useFileNavHistory
  const useHistoryView: typeof import('../stores/useHistoryView').useHistoryView
  const useLocalFolderManualOrder: typeof import('../stores/localFolderOrder').useLocalFolderManualOrder
  const useLocalFolderOrders: typeof import('../stores/localFolderOrder').useLocalFolderOrders
  const useLocalFolderTargetPicker: typeof import('../stores/useLocalFolderTargetPicker').useLocalFolderTargetPicker
  const useNotebookAiChats: typeof import('../stores/useNotebookAiChats').useNotebookAiChats
  const useNotebooks: typeof import('../stores/useNotebooks').useNotebooks
  const usePages: typeof import('../stores/pages/index').usePages
  const useQuickNote: typeof import('../stores/useQuickNote').useQuickNote
  const useSettings: typeof import('../stores/settings/index').useSettings
  const useSidebarView: typeof import('../stores/useSidebarView').useSidebarView
  const useTabs: typeof import('../stores/useTabs').useTabs
  const useWorkspaceViewport: typeof import('../stores/useWorkspaceViewport').useWorkspaceViewport
  const writeTabSplitForWindow: typeof import('../stores/useEditorSplit').writeTabSplitForWindow
}
// for type re-export
declare global {
  // @ts-ignore
  export type { LocalFolderOrderMap } from '../stores/localFolderOrder'
  import('../stores/localFolderOrder')
  // @ts-ignore
  export type { AccentColor, AISettings, CustomAction, CustomFonts, DesktopHotkeyStatus, DesktopHotkeyStatusState, DesktopSettings, FontConfig, PrivacySettings, SearchProvider, SettingsState, Theme, UIFontSize } from '../stores/settings/index'
  import('../stores/settings/index')
  // @ts-ignore
  export type { AiActivityPhase } from '../stores/useAiStatus'
  import('../stores/useAiStatus')
  // @ts-ignore
  export type { EditorSplitStore } from '../stores/useEditorSplit'
  import('../stores/useEditorSplit')
  // @ts-ignore
  export type { FileNavLocation } from '../stores/useFileNavHistory'
  import('../stores/useFileNavHistory')
  // @ts-ignore
  export type { LocalFolderTargetPickerMode } from '../stores/useLocalFolderTargetPicker'
  import('../stores/useLocalFolderTargetPicker')
  // @ts-ignore
  export type { NotebookAiChatsState, NotebookAiConversation, NotebookAiNotebookChatState } from '../stores/useNotebookAiChats'
  import('../stores/useNotebookAiChats')
  // @ts-ignore
  export type { LocalFolderLoadState, LocalFolderLoadStatus, Notebook } from '../stores/useNotebooks'
  import('../stores/useNotebooks')
  // @ts-ignore
  export type { QuickNoteDrafts, QuickNoteSlot, QuickNoteSlotNames } from '../stores/useQuickNote'
  import('../stores/useQuickNote')
  // @ts-ignore
  export type { TabItem, TabType } from '../stores/useTabs'
  import('../stores/useTabs')
}
