// Generated by Goose Note auto-import configuration.
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}
declare global {
  const BEAM_MIN_ACTIVE_MS: typeof import('../components/ui/ai-motion').BEAM_MIN_ACTIVE_MS
  const Badge: typeof import('../components/ui/badge').Badge
  const Button: typeof import('../components/ui/button').Button
  const Command: typeof import('../components/ui/command').Command
  const CommandDialog: typeof import('../components/ui/command').CommandDialog
  const CommandEmpty: typeof import('../components/ui/command').CommandEmpty
  const CommandGroup: typeof import('../components/ui/command').CommandGroup
  const CommandInput: typeof import('../components/ui/command').CommandInput
  const CommandItem: typeof import('../components/ui/command').CommandItem
  const CommandList: typeof import('../components/ui/command').CommandList
  const ContextMenu: typeof import('../components/ui/context-menu').ContextMenu
  const ContextMenuContent: typeof import('../components/ui/context-menu').ContextMenuContent
  const ContextMenuGroup: typeof import('../components/ui/context-menu').ContextMenuGroup
  const ContextMenuItem: typeof import('../components/ui/context-menu').ContextMenuItem
  const ContextMenuLabel: typeof import('../components/ui/context-menu').ContextMenuLabel
  const ContextMenuPortal: typeof import('../components/ui/context-menu').ContextMenuPortal
  const ContextMenuSeparator: typeof import('../components/ui/context-menu').ContextMenuSeparator
  const ContextMenuShortcut: typeof import('../components/ui/context-menu').ContextMenuShortcut
  const ContextMenuSub: typeof import('../components/ui/context-menu').ContextMenuSub
  const ContextMenuSubContent: typeof import('../components/ui/context-menu').ContextMenuSubContent
  const ContextMenuSubTrigger: typeof import('../components/ui/context-menu').ContextMenuSubTrigger
  const ContextMenuTrigger: typeof import('../components/ui/context-menu').ContextMenuTrigger
  const Dialog: typeof import('../components/ui/dialog').Dialog
  const DialogClose: typeof import('../components/ui/dialog').DialogClose
  const DialogContent: typeof import('../components/ui/dialog').DialogContent
  const DialogDescription: typeof import('../components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('../components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('../components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('../components/ui/dialog').DialogOverlay
  const DialogShell: typeof import('../components/ui/dialog-shell').DialogShell
  const DialogTitle: typeof import('../components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('../components/ui/dialog').DialogTrigger
  const DropdownMenu: typeof import('../components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuContent: typeof import('../components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuIconSlot: typeof import('../components/ui/dropdown-menu').DropdownMenuIconSlot
  const DropdownMenuItem: typeof import('../components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuRadioGroup: typeof import('../components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('../components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('../components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuTrigger: typeof import('../components/ui/dropdown-menu').DropdownMenuTrigger
  const FLOATING_MENU_CLOSE_MS: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_CLOSE_MS
  const FLOATING_MENU_EASE_IN: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_EASE_IN
  const FLOATING_MENU_EASE_OUT: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_EASE_OUT
  const FLOATING_MENU_OPEN_MS: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_OPEN_MS
  const FLOATING_MENU_SCALE: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_SCALE
  const FLOATING_MENU_SHIFT_PX: typeof import('../components/ui/floating-menu-motion').FLOATING_MENU_SHIFT_PX
  const FeatureToastCard: typeof import('../components/ui/feature-toast-card').FeatureToastCard
  const IconButton: typeof import('../components/ui/icon-button').IconButton
  const ImageExportThemeSelector: typeof import('../components/ui/image-export-theme-selector').ImageExportThemeSelector
  const Input: typeof import('../components/ui/input').Input
  const Kbd: typeof import('../components/ui/kbd').Kbd
  const Label: typeof import('../components/ui/label').Label
  const NOTEBOOK_MENU_CLOSE_MS: typeof import('../components/ui/floating-menu-motion').NOTEBOOK_MENU_CLOSE_MS
  const NOTEBOOK_MENU_OPEN_MS: typeof import('../components/ui/floating-menu-motion').NOTEBOOK_MENU_OPEN_MS
  const ORB_PHASE_HOLD_MS: typeof import('../components/ui/ai-motion').ORB_PHASE_HOLD_MS
  const ORB_VISIBLE_MIN_MS: typeof import('../components/ui/ai-motion').ORB_VISIBLE_MIN_MS
  const Popover: typeof import('../components/ui/popover').Popover
  const PopoverAction: typeof import('../components/ui/popover').PopoverAction
  const PopoverAnchor: typeof import('../components/ui/popover').PopoverAnchor
  const PopoverContent: typeof import('../components/ui/popover').PopoverContent
  const PopoverTrigger: typeof import('../components/ui/popover').PopoverTrigger
  const ScrollArea: typeof import('../components/ui/scroll-area').ScrollArea
  const SelectableCard: typeof import('../components/ui/selectable-card').SelectableCard
  const Separator: typeof import('../components/ui/separator').Separator
  const SuccessToastIcon: typeof import('../components/ui/sonner').SuccessToastIcon
  const Switch: typeof import('../components/ui/switch').Switch
  const THINKING_PLACEHOLDER_MIN_MS: typeof import('../components/ui/ai-motion').THINKING_PLACEHOLDER_MIN_MS
  const TOOLTIP_DELAY_MS: typeof import('../components/ui/tooltip-delay').TOOLTIP_DELAY_MS
  const Toaster: typeof import('../components/ui/sonner').Toaster
  const Tooltip: typeof import('../components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('../components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('../components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('../components/ui/tooltip').TooltipTrigger
  const TriggerChild: typeof import('../components/ui/trigger-child').TriggerChild
  const badgeVariants: typeof import('../components/ui/badge').badgeVariants
  const buttonVariants: typeof import('../components/ui/button').buttonVariants
  const floatingMenuFromTransform: typeof import('../components/ui/floating-menu-motion').floatingMenuFromTransform
  const floatingMenuMotionStyle: typeof import('../components/ui/floating-menu-motion').floatingMenuMotionStyle
  const floatingMenuOrigin: typeof import('../components/ui/floating-menu-motion').floatingMenuOrigin
  const resolveTooltipDelayDuration: typeof import('../components/ui/tooltip-delay').resolveTooltipDelayDuration
  const showDeleteReceipt: typeof import('../components/ui/delete-receipt').showDeleteReceipt
  const toast: typeof import('../components/ui/sonner').toast
  const useMinHoldActive: typeof import('../components/ui/ai-motion').useMinHoldActive
}
// for type re-export
declare global {
  // @ts-ignore
  export type { BadgeProps } from '../components/ui/badge'
  import('../components/ui/badge')
  // @ts-ignore
  export type { ButtonProps } from '../components/ui/button'
  import('../components/ui/button')
  // @ts-ignore
  export type { DialogProps } from '../components/ui/dialog'
  import('../components/ui/dialog')
  // @ts-ignore
  export type { FloatingMotionMode, FloatingMotionStatus } from '../components/ui/floating-menu-motion'
  import('../components/ui/floating-menu-motion')
  // @ts-ignore
  export type { IconButtonProps } from '../components/ui/icon-button'
  import('../components/ui/icon-button')
  // @ts-ignore
  export type { SelectableCardProps } from '../components/ui/selectable-card'
  import('../components/ui/selectable-card')
}
